### ISSUE TITLE
Why the color is not display when run on local

### ISSUE THREAD

**Issue by intfish123** [redpanda-data/console#1016]
![image](https://github.com/redpanda-data/console/assets/35686254/532b67f7-abd2-4224-88f8-dace94096c03)

**Comment by weeco** [comment]
I'm not sure what the question is?

**Comment by intfish123** [comment]
> I'm not sure what the question is?

The color are displayed normally when I using docker to run.  there are some difference of css style between local and docker.

![image](https://github.com/redpanda-data/console/assets/35686254/9e477d24-6a11-4e2c-a03c-33646210da1d)
