### ISSUE TITLE
Missing Pagination on Connectors List

### ISSUE THREAD

**Issue by jseparovic** [redpanda-data/console#1032]
I noticed one environment where the connector pagination list does not show up:

![image](https://github.com/redpanda-data/console/assets/4665758/73e5bb88-f665-4b77-95fc-ca00162b982c)

On a second environment, it works fine. I'm using the latest Docker images.

**Comment by jseparovic** [comment]
It could be due to the length of the connector names? I added a quite a bit more characters to the connector names just before I noticed this issue. But also, this particular env never had more than 6 connectors previously.

**Comment by weeco** [comment]
Hey @jseparovic ,
could you test whether this issue persists with the latest Console version (e.g. `docker pull redpandadata/console-unstable:master-2b63dfe`) ?

**Comment by weeco** [comment]
Thanks for the feedback @jseparovic . I extracted your feedback regarding the horizontal overflow into a new issue: https://github.com/redpanda-data/console/issues/1050 and will close this issue

**Comment by jseparovic** [comment]
@weeco It broke again in the following build it seems:
![image](https://github.com/redpanda-data/console/assets/4665758/08af4208-6a5a-48bd-8f67-b8873fa7a458)

**Comment by jseparovic** [comment]
redpandadata/console:v2.3.1 works ok
redpandadata/console:v2.4.1 has no pagination again

**Comment by jseparovic** [comment]
@weeco Looks good. Only problem is the connector filter is gone again which was there in v2.3.1
![image](https://github.com/redpanda-data/console/assets/4665758/26efdaf0-3afa-4b15-8375-6d2aa33110fb)


Here is v2.3.1 with the connector filter:
![image](https://github.com/redpanda-data/console/assets/4665758/1eda2a93-7cd3-47d1-a11e-3c5c380c12a7)
