### ISSUE TITLE
Horizontal overflow in tables

### ISSUE THREAD

**Issue by weeco** [redpanda-data/console#1050]
Tables that contain columns with very long values the table is overflowing and exceeds the panel in which it is wrapped. The horizontal scroll does not work. We should ensure that all tables (e.g. topics, schemas, connectors, ...) can handle long values. Specifically topic names can be up to 254 chars, and for other dynamic values such as the connector or schema name we should assume a similar max length that we should support.

![image](https://github.com/redpanda-data/console/assets/4665758/d2917fce-9c32-45c8-8410-980aa375a834)

Looks ok after adding overflow setting in chrome inspect:

![image](https://github.com/redpanda-data/console/assets/4665758/0bcc49e6-902a-4587-88f7-3a9ce20b1e8a)

![image](https://github.com/redpanda-data/console/assets/4665758/8039ca8a-1c75-4b67-8705-a8a4d94d8acf)

_Originally posted by @jseparovic in https://github.com/redpanda-data/console/issues/1032#issuecomment-1918733984_ , I added more context.

**Comment by ivpanda** [comment]
A quick fix for this: it's OK to truncate the connector name here. A user's primary focus here is whether or not the connector is healthy or not. They can always click into it to see more information, including the full name. 

Mo and I are looking into improving tables more holistically.

**Comment by jseparovic** [comment]
Can you make this a configurable setting? I’m not a fan of truncating the name. This is currently the only way I can find the connector I’m looking for. A filter at the top to search for a connector name would be useful too. Configurable columns too would be ideal, in my setup I would get rid of everything except connector name.

**Comment by weeco** [comment]
We should definetely add a quicksearch input for searching connectors. I'm surprised we do not already have one since we have community users running more than 1k connectors in their environment!

Configurable columns should be possible too! For example on the "Topics > List messages" tab we have a cogwheel in the table header row where you can configure the table settings including what columns you want to see. We could do something similar for the connectors too!

**Comment by ivpanda** [comment]
To update this, we decided in a Slack discussion and through some feedback from CS to allow long table names to wrap instead of truncating: 

<img width="1014" alt="image" src="https://github.com/redpanda-data/console/assets/129790723/542b2ba5-5123-4ffc-bdeb-a4f4c29daefb">

Then, on the individual pages, we will show the names with the following pattern: 

<img width="1022" alt="image" src="https://github.com/redpanda-data/console/assets/129790723/6e8821ae-a195-4b87-b8e0-a9340e68bba7">

The title will be **Topic** or **Connector** with the full name underneath, copyable.

**Comment by weeco** [comment]
Fixed via https://github.com/redpanda-data/console/pull/1159
