### ISSUE TITLE
Copy value on message returns payload three times

### ISSUE THREAD

**Issue by ErykCh** [redpanda-data/console#1054]
Hi,

copy value action on message returns json with metadata.

In this, the payload itself is given three times.

![image](https://github.com/redpanda-data/console/assets/95491982/e9533ade-6544-4d8b-96f2-33665daf03c7)

**Comment by rikimaru0345** [comment]
Next version will include a new "Copy Message" context menu item (with the fixes of this issue, removing normalizedPayload valueJson, and sometimes duplicate binary data...) which copies the full message object with headers, key and value, along with raw binary data.

Copy Key and Copy value have been changed to only copy the inner payload content (ie what is being shown in the columns of the table).

![image](https://github.com/redpanda-data/console/assets/28133019/a18572f0-99a0-4bb3-9271-fe565d0edbf5)

**Comment by weeco** [comment]
Fixed via https://github.com/redpanda-data/console/pull/1057
