### ISSUE TITLE
Lazyload messages that are too large

### ISSUE THREAD

**Issue by weeco** [redpanda-data/console#1059]
The backend flags messages that exceed a certain size limit. This flag is used by the frontend to determine whether we would try to render this message in the DOM or not. If the sum of all messages is too large this will crash the frontend application due to a hard-limit of resources in the browser.

For messages that are too large we show messages like this:

![ss-SjOEM8kn](https://github.com/redpanda-data/console/assets/23424570/783f6451-ff18-41e0-bb68-64190ba22e21)

We would like to add the possibility that they can click a button which tries to load a specific message. We should make clear that this could crash the application (usually noticed as a frozen browser window) if the message is too large.

**Comment by ivpanda** [comment]
Design proposal: 

![image](https://github.com/redpanda-data/console/assets/129790723/26104df2-e83a-481d-ba54-a6352eab5e38)

I acknowledge that we may not know the limit, though, so it's fine for the text to just be "This message has been omitted due to our display limits. Loading it could cause the system to slow down or freeze." 

Tagging @micheleRP for text review

**Comment by micheleRP** [comment]
Suggested edits: 

_Message content is too large and has been omitted._ 
change to
_Message size exceeds the display limit._ 

_This message is larger than our display limit (X MiB). Loading it could cause the system to slow down or freeze._ 
change to
_Because this message size exceeds the diplay limit, loading it could cause performance degradation._

**Comment by rikimaru0345** [comment]
This is how it looks right now in a WIP branch

https://github.com/redpanda-data/console/assets/28133019/fd586c03-2e85-4714-8fdb-c20234305867

**Comment by rikimaru0345** [comment]
> could you pleeease change this message value text

Sure, sorry about that. I changed it from
`Message size exceeds the display limit, loading it could cause performance degradation`
to
`Because this message size exceeds the display limit, loading it could cause performance degradation.`

**Comment by 1nutzername** [comment]
Hey, I'm a bit late. Is it possible to set a flag to skip this check and just display the messages as seen last in version 2.3.10?
