### ISSUE TITLE
Missing filter for searching by connector name

### ISSUE THREAD

**Issue by weeco** [redpanda-data/console#1091]
The connector filter is gone again which was there in v2.3.1
![image](https://github.com/redpanda-data/console/assets/4665758/26efdaf0-3afa-4b15-8375-6d2aa33110fb)

Here is v2.3.1 with the connector filter:
![image](https://github.com/redpanda-data/console/assets/4665758/1eda2a93-7cd3-47d1-a11e-3c5c380c12a7)

_Originally posted by @jseparovic in https://github.com/redpanda-data/console/issues/1032#issuecomment-1931295401_

**Comment by jvorcak** [comment]
Fixed https://github.com/redpanda-data/console/pull/1094
