### ISSUE TITLE
Incorrect warning raised when displaying topics sizes

### ISSUE THREAD

**Issue by epot** [redpanda-data/console#1125]
I noticed the following warning when connecting the redpanda console to a locally deployed kafka cluster of 2 brokers. 
<img width="1236" alt="Screenshot 2024-02-14 at 11 25 51 AM" src="https://github.com/redpanda-data/console/assets/578179/d8a906e2-c8bc-4d46-aa77-cbac280b35db">

I initially thought I did something wrong with my Kafka cluster, but after carefully reading the redpanda console code, I am no longer certain it is the case. I'd like to confirm my understanding though. If you look at the `errorByBrokerID` map [here](https://github.com/redpanda-data/console/blob/v2.4.3/backend/pkg/console/log_dir_topic.go#L78), it seems to be only filled with maximum one key which is `res.BrokerMetadata.NodeID`. Similarly the `partitionLogDirs` map is always filled with an element with the same key `replicaDirs[res.BrokerMetadata.NodeID] = d`. 

So when you enter this piece of code:
```
for _, replicaID := range partition.Replicas {
// Have we got a log dir response for this specific partition replica? If not we want to create a
// dummy response that contains a proper error message for the requested replica.
// Thus we first look up the per broker errors, but we also return a fallback message if we haven't
// got an error/response back from the broker.
if _, exists := partitionLogDirs[topicName][partitionID][replicaID]; !exists {
	err, errExists := errorByBrokerID[replicaID]
	if !errExists {
		// We should never run into this. We should always receive a proper error if responses are missing!
		err = fmt.Errorf("haven't got a log dir response for this replica even though it had been requested")
	}
(...)
```
it seems it will always return an error once you have one replica that is different from `res.BrokerMetadata.NodeID`.

Could you confirm I didn't miss anything obvious?

Cheers,
epot

**Comment by weeco** [comment]
The `errorByBrokerID` map is only filled with entries if there was an error in the DescribeLogDirs response by the respective broker. An error is either set if the entire request failed (e.g. timeout/broker not reachable, no permissions etc), or if the log dir response failed (e.g. storage is broken), see:

https://github.com/redpanda-data/console/blob/d3256b194cad5facb9c307614d8ff3223ca93a45/backend/pkg/console/log_dir_topic.go#L82

https://github.com/redpanda-data/console/blob/d3256b194cad5facb9c307614d8ff3223ca93a45/backend/pkg/console/log_dir_topic.go#L89


If there is at least one such error and we know that at least one partition-replica is hosted on a broker that returned an error we can no longer be certain about the topic size. If there's no error in the response no error will be set and the map should be empty.

**Comment by weeco** [comment]
> But do you agree that in the current implementation only one broker can be put into errorByBrokerID?

No, one error for each broker.

> In any case, I think what bugs me more is that from my understanding we only put one replicaID in the partitionLogDirs map, which will always prompts the warning I see as soon as your partition is replicated on more than 1 broker.

That's not right. We put a map of `partitionLogDir` where the key is replica id. It seems there's a misunderstanding of how maps work.

**Comment by epot** [comment]
When I read this method, we call it with one metadata response `metadata *kmsg.MetadataResponse` and we use the `res.BrokerMetadata.NodeID` everywhere to fill the maps when we need a `replicaID`. Can you show me where we fill partitionLogDir with another `replicaID`, I am sure I am missing something obvious.

**Comment by weeco** [comment]
The `res.BrokerMetadata.NodeID` is accessed inside a for each loop of the DescribeLogDirs `responses` (this is a slice of responses, where each entry refers to one response from a node). 

The metadata that is passed to this function is only used for iterating through all topics in the cluster and finding the replicas for every individual partition, so that we know whose DescribeLogDir responses we must have to be certain about the total size of each topic.

**Comment by epot** [comment]
Ok, but then I don't see where in the code we add one entry in the `partitionLogDir` map from a different replica than the one coming from the metadata reponse. Sorry :(

**Comment by epot** [comment]
@weeco do you understand what I mean? I don't think we are populating the map with any other replica than `res.BrokerMetadata.NodeID` before we raise the error basically.

**Comment by epot** [comment]
Sorry I spent more time on this and it seems I completely imagined things, it makes more sense now. I don't know why I was convinced that `res.BrokerMetadata.NodeID` was coming from the `metadata` parameter of the method but it's not the case at all. And I can't reproduce what I have seen locally with a local kafka cluster of 2 nodes.
