### ISSUE TITLE
Delete records should be available for compact,delete topics

### ISSUE THREAD

**Issue by weeco** [redpanda-data/console#1151]
Topics that use [compact,delete] support deleting records. However the frontend disables this option in that case:

![image](https://github.com/redpanda-data/console/assets/23424570/7f771080-12b3-449f-93ef-080975788c4b)

**Comment by jvorcak** [comment]
<img width="1289" alt="Screenshot 2024-03-19 at 10 46 19" src="https://github.com/redpanda-data/console/assets/1083817/4f2b9f0e-4024-41c5-9d20-c83f16d2657c">

@weeco what do I need in order to create this policy?

**Comment by weeco** [comment]
@jvorcak Select both delete and compact in that dialog if possible (unsure if its a multiselect)

**Comment by jvorcak** [comment]
@weeco it's a select, so should I also make it a multi select?

**Comment by weeco** [comment]
You can leave it as a select and add a compact,delete method too.
