### ISSUE TITLE
Unstable order in Kafka ACL view

### ISSUE THREAD

**Issue by weeco** [redpanda-data/console#1164]
The order of the ACLs here is unstable. Upon new refreshes the order shuffles, randomly. Actively clicking the Principal column to sort by principal name has no effect:

Initial page
![ss-xecFh2z1](https://github.com/redpanda-data/console/assets/23424570/dd558a11-5c63-476c-b003-9845f2a0ce48)

First refresh
![ss-cT0qIn3q](https://github.com/redpanda-data/console/assets/23424570/db231662-e023-4dce-bf72-d47d0edcd242)

**Comment by jvorcak** [comment]
@weeco is this still relevant with the new UI? I think we can close this one? Can you confirm?

![Image](https://github.com/redpanda-data/console/assets/1083817/ae3a95f7-e291-4600-8fe0-6d4a05aae281)

**Comment by weeco** [comment]
Confirmed, the order is stable now. Not sure in what order it's being presented, but it's stable!
