### ISSUE TITLE
[Feature Request] REST serde

### ISSUE THREAD

**Issue by wassim-k** [redpanda-data/console#1177]
First of all, thanks for the great work you've done on this console. We've started using it recently and love it!

We have a use case where IoT devices publish their data to MQTT using a MessagePack format and then that gets forwaded to a topic. But the format is quite complex with custom MessagePack formatters and resolvers implemented in C# with schema versioning support, and C# compliant GUID representation, and so on. Unfortunately, OOB MsgPack doesn't meet our requirements.

If you're open to the idea of introducing a REST API based serde, which forwards the binary payload of a kafka message to an endpoint and expects JSON response in return. Then, I have implemented it here #1141, we have been using this serde in our production environment for a while now and its been working great.

Thanks for your consideration.

**Comment by weeco** [comment]
@wassim-k I created https://github.com/redpanda-data/console/issues/1192 . Please feel free to upvote to signal the demand there :).
