### ISSUE TITLE
Select component z-Index problem in ACL Modal

### ISSUE THREAD

**Issue by weeco** [redpanda-data/console#1178]
The following screenshot explains it pretty well:

![ss-WRMm0MwN](https://github.com/redpanda-data/console/assets/23424570/b89ce0b8-d588-41bd-8500-c21edbb15ce9)

**Comment by rikimaru0345** [comment]
will be fixed when rbac is merged.

**Comment by jvorcak** [comment]
Since the PR was merged, I'll close this issue
