### ISSUE TITLE
Cannot produce Avro messages - no schema id specified

### ISSUE THREAD

**Issue by tukak** [redpanda-data/console#1182]
We're trying to use Redpanda Console with our Kafka (MSK) cluster and a self hosted Schema Registry.
Console is installed on Kubernetes using the latest helm chart (0.7.24), version of the app is v2.4.5.
When trying to produce Avro message, we can select the schema and version, but after clicking on Produce there's a `no schema id specified` error - see screenshot

<img width="659" alt="image" src="https://github.com/redpanda-data/console/assets/1147796/f6c59bdc-ce35-44c7-941f-d3fc7c87c992">

Console logs the same error to output
```
{"level":"warn","ts":"2024-03-18T16:24:31.628Z","logger":"error_log","msg":"","timestamp":"2024-03-18T16:24:31Z","procedure":"/redpanda.api.console.v1alpha1.ConsoleService/PublishMessage","request_duration":"99.086µs","status_code":"invalid_argument","request_size_bytes":433,"peer_address":"172.21.7.4","error":"invalid_argument: no schema id specified"}
```

In the browser I see an error 400 Bad Request on request to `redpanda.api.console.v1alpha1.ConsoleService/PublishMessage` and the payload indeed does not contain any schema id:
```
{"topic":"event.note_autolink","partitionId":-1,"compression":"COMPRESSION_TYPE_SNAPPY","key":{"encoding":"PAYLOAD_ENCODING_TEXT","data":"MTIzNDU2"},"value":{"encoding":"PAYLOAD_ENCODING_AVRO","data":"ewoJInNwYWNlX2lkIjogNTA1MjkwLAoJIm5vdGVfdXVpZCI6ICI4OTAxNWRmZS02MjUyLTRiMDItYjNmYi1jZjI5ODUwYjAxMjUiLAoJIm5vdGVfc3VtbWFyeSI6ICJSb25hbGRvIGlzIGZhY2luZyBjb25zZXF1ZW5jZXMgZm9yIGhpcyBjb25kdWN0IGR1cmluZyBhIGdhbWUgd2hlcmUgaGUgcmVzcG9uZGVkIHRvIHBlcnNpc3RlbnQgY2hhbnRzIG9mIE1lc3NpIGJ5IGN1cHBpbmcgYW4gZWFyIGFuZCB0aHJ1c3RpbmcgaGlzIGhhbmQgdG93YXJkcyBoaXMgcGVsdmlzLCByZXN1bHRpbmcgaW4gaGltIG1pc3NpbmcgaGlzIHRlYW0ncyBuZXh0IGdhbWUuIiwKCSJoaWVyYXJjaHlfaXRlbV91dWlkIjogIjI4NGVkMmM1LWIxMDEtNDkwMy05NzAyLTUwZDg2NzY3OWYyNCIKfQ=="}}
```

Can it be some error in our setup or is it a bug? Can I help with any other info to debug it?

**Comment by weeco** [comment]
Hey @tukak ,
in fact producing typed records should be hidden in the UI. We prepared development on this feature, but haven't been able to finish it. Apologies for the confusion, I'll make sure it'll be hidden so that no one wastes valuable time on trying to get this work.

**Comment by tukak** [comment]
@weeco thank you for the clarification - I hope the feature will land some time

**Comment by hhromic** [comment]
Ah dang, just stumbled on this same issue today. Didn't know this feature is still WIP :')
Anyway looking forward for its eventual implementation and launch!
The idea of publishing Avro records directly from the console UI is so good and we didn't know how much we need this!

**Comment by hidiryuzuguzel** [comment]
Hello, it is a great feature which is missing :( Any plan to implement it in the near future? Thx.
