### ISSUE TITLE
Gracefully handle failed /schemas/types requests

### ISSUE THREAD

**Issue by weeco** [redpanda-data/console#1197]
For very old schema registries or semi-compatible implementations this endpoint may not exist and return a 404 instead. In that case we should assume a `['AVRO']` response and possibly show a warning tooltip on the schema list page.

Currently the schema registry page just fails in that case:

![image](https://github.com/redpanda-data/console/assets/23424570/cdf4a495-09e3-45c7-a9f9-4051b1764618)

**Comment by twmb** [comment]
Closed by #1249
