### ISSUE TITLE
Edit topic configuration

### ISSUE THREAD

**Issue by analogue** [redpanda-data/console#125]
Would be nice to be able to edit topic configuration on this page: ```http://<server>:<port>/topics/<topic name>?#configuration```

**Comment by debMan** [comment]
Any update on this issue?

**Comment by fareye-baldeep** [comment]
Any plans to pick this issue?

**Comment by weeco** [comment]
Hey @fareye-baldeep ,
yes see this branch: https://github.com/redpanda-data/console/tree/edit-topic-configs

The feature is almost done and will be included in the next release :).

**Comment by weeco** [comment]
Edit topic configs has been added and will be included in the next release (planned for end of next week)
