### ISSUE TITLE
Connector logs tab is always shown

### ISSUE THREAD

**Issue by weeco** [redpanda-data/console#1258]
The logs tab in the connector details page is shown even if the logs topic for connectors does not exists. This is confusing to users, because they will expect logs here, even though we will never receive any logs:

![image](https://github.com/redpanda-data/console/assets/23424570/dabf100b-58b6-4dce-812e-d21b7187caf9)

**Comment by jvorcak** [comment]
![Screenshot 2024-06-12 at 15 33 48](https://github.com/redpanda-data/console/assets/1083817/a3075884-3b9d-47a5-b783-936059cb99f0)

WIP Version to be approved or rephrased

**Comment by weeco** [comment]
@jvorcak I think the tooltip as shown in your screenshot is fine. Because Console may be used by folks that don't use any Redpanda products we can not necessarily direct them to a "fix". In some environments it's simply expected that they won't have access to connector logs.

**Comment by jvorcak** [comment]
@weeco good input, thanks. In case the phrasing is also OK, we can merge the PR, I'm making it ready to be reviewed.
