### ISSUE TITLE
disable error message "Errors were encoutnered when deserializing this message"

### ISSUE THREAD

**Issue by aushafy** [redpanda-data/console#1277]
Hi,

Previously I was using Redpanda console with version v2.2.3 and I upgrade it to latest version v2.4.x but the topics messages page shown error _There were issues deserializing the value_ it is possible to ack this error and disable for some reason as previous version v2.2.3 and defaulted to binary hex format message ?

or may you have another option to disable this error deserializing ?

**Comment by weeco** [comment]
Hello,
the latest version is v2.6.0. We indeed worked on the message viewer. You would still see the binary presentation of this when expanding the message row. Additionally you can also specify the deserialization strategy which defaults to "Auto" and use "Binary" instead to have it rendered as hex immediately.

**Comment by aushafy** [comment]
okay got it. the values appear if I expand each row. thanks, this issue shall be close later
