### ISSUE TITLE
docker container resource requests and limits

### ISSUE THREAD

**Issue by arman-sydikov** [redpanda-data/console#1278]
https://hub.docker.com/r/redpandadata/console
We use the above docker image to run redpanda-console as a pod in kubernetes cluster, as you can see from the screenshot, we have 107308070 messages in our topic, everything works fine until we select START OFFSET = Oldest:

![Screenshot 2024-06-08 at 15 13 05](https://github.com/redpanda-data/console/assets/10354348/41a3fe53-fb75-4b40-8026-9d4f5e08fdde)

It starts consuming messages from the beginning and stops after several seconds with the following error:

![Screenshot 2024-06-08 at 15 25 41](https://github.com/redpanda-data/console/assets/10354348/c63de468-35cb-4589-bc94-88c9845fc040)

From the logs, we can see that the pod was restarted 5 seconds after redpanda started consuming messages.

![Screenshot 2024-06-08 at 15 33 00](https://github.com/redpanda-data/console/assets/10354348/383d0583-df1b-4998-a6c6-e2ab0cf4e5cc)

Here are the requests and limits we set for our pod:

```
Limits:
  cpu:     100m
  memory:  700Mi
Requests:
  cpu:      50m
  memory:   600Mi
```

Could that be the reason of pod restarts?
What are the recommended memory and cpu limits for redpanda-console container?

**Comment by weeco** [comment]
Hey @arman-sydikov ,
yes the resource constraints may be the reason. I'd recommend 2Gi of Memory and a burstable CPU configuration, since the only resource intensive task is a message search such as you were performing. If acceptable in your environment, you may want to remove the CPU limit entirely, but a limit of 1vCPU sounds reasonable too. The number of messages it can process per second is likely to be CPU bound. In our experience it is around ~50k messages / second for each core that it can use.

**Comment by arman-sydikov** [comment]
@weeco 

thank you for the advise, I have increased the limits to 2 cpu and 2.5Gi memory

```
Limits:
  cpu:     2
  memory:  2560Mi
Requests:
  cpu:      50m
  memory:   50Mi
```

now it doesn't restart, but stops after consuming about 45 Gib /  50 million messages with the following error:

![Screenshot 2024-06-09 at 09 12 33](https://github.com/redpanda-data/console/assets/10354348/9926da20-40b6-4649-a5fa-feb137afe803)

**Comment by weeco** [comment]
What Console version are you using?

**Comment by arman-sydikov** [comment]
> What Console version are you using?

Redpanda Console (Platform Version v24.1)
(built May 30, 2024)
788406B

**Comment by weeco** [comment]
Can you tell how long this search was running? I think we have some hardcoded upper limit like 35minutes or so.
