### ISSUE TITLE
How to enable login?

### ISSUE THREAD

**Issue by arman-sydikov** [redpanda-data/console#1307]
We deploy `redpanda console` as a kubernetes pod, everything works as expected.
No we need to add a login authentication, so it would only be available to logged users.

I looked at these environment variables, but couldn't figure out which one we need.
https://github.com/redpanda-data/console/blob/master/docs/config/console.yaml

How to enable login to `redpanda console`?

**Comment by weeco** [comment]
Hey @arman-sydikov ,
the login/authentication is an enterprise feature and will only become usable if you have a valid license. If that's the case please have a look at the documentation here: https://docs.redpanda.com/current/manage/security/console/authentication/
