### ISSUE TITLE
Message viewer: Specific selection of deserializers doesn't render messages

### ISSUE THREAD

**Issue by weeco** [redpanda-data/console#1356]
When a specific encoding type is selected as part of the ListMessages request the backend seems to ignore it:

![ss-FFtI8ajg](https://github.com/user-attachments/assets/8c23b40d-619f-43f1-9ca8-822355754199)

![ss-sQjDN6Hd](https://github.com/user-attachments/assets/8980b913-b9dc-4047-8f5b-07073cbce487)

**Comment by weeco** [comment]
@rikimaru0345 What conditions must be fulfilled to have the troubleshoot report show up for the key? I'm handling the case where the user specifies a specific encoding for either key/value, which failed to desserialize. I think in that case we should show that it failed as we always do. The only difference would be that the trouble shoot report has a single entry in that case.

![ss-cG29Ewyd](https://github.com/user-attachments/assets/89831643-6203-4446-bf75-69b999d94496)

**Comment by rikimaru0345** [comment]
> What conditions must be fulfilled to have the troubleshoot report show up for the key?

`(payload.troubleshootReport && payload.troubleshootReport.length > 0)`

This is the same for key and value.
The entry must be set, and have one or more entries.
Also, you must expand the message, in your screenshot you are only looking at the preview / collapsed messages.
