### ISSUE TITLE
Inconsistent display of inactive consumers

### ISSUE THREAD

**Issue by boris-faniuk-n26** [redpanda-data/console#1364]
We have a Kafka topic that has multiple consumers. 
Also, there's an instance of this topic in several different environments.
At some point in time we had to temporarily stop most of the consumers of this topic (except few).
When viewing this topic in Redpanda console, we can see different state across environments:
1. in some environments consumer list displays only consumers that are currently active
2. in some environments consumer list displays all ever running consumers, stopped consumers have no partitions assigned

What is the correct expected behaviour (I would say "only consumers that are currently running", but maybe there's another opinion). Maybe there's a setting that controls this?

Thanks for any hints!

**Comment by weeco** [comment]
Could you clarify what you mean by different environments? 

I assume you are referring to completely different clusters and therefore also different situations / timings. Would be great to have some screenshots to get a better impression. Information about **consumer groups** (i.e. committed offsets) are always supposed to be there, regardless of the state of the consumer group (empty, rebalancing etc). Information about the consumer group **members** are only expected if one or more consumers are active. We use the Kafka API to describe the consumer groups.

**Comment by boris-faniuk-n26** [comment]
This is an example (I have hidden real topic and consumer names), but you can see this consumer group has consumed a single topic, currently not active, but still present in consumers list.

![Screenshot 2024-08-08 at 22 12 44](https://github.com/user-attachments/assets/3f99e81e-354e-4e91-a142-a6c7ea9ce856)

<img width="1144" alt="Screenshot 2024-08-08 at 22 14 25" src="https://github.com/user-attachments/assets/30970537-759b-42ce-b7f6-f1408e12bbca">

**Comment by weeco** [comment]
So the `Consumers` tab (first screenshot) is listing all consumer groups that have committed offsets for one or more partitions for the topic you are looking at. They basically show all consumer groups along with the group lag.

The second screenshot show the lag per partition and it also shows that there's no active member (see group state and "Assigned member" column). It's not contrary.

**Comment by boris-faniuk-n26** [comment]
Do you mean that correct behaviour is to show all ever running consumers, even stopped ones?
But then why another cluster shows only active consumers? There are another consumers that committed offsets there, but they are not displayed.

**Comment by weeco** [comment]
> Do you mean that correct behaviour is to show all ever running consumers, even stopped ones?

Yes, committed offsets are supposed to be stored (for up to 7d by default) even if the group is empty / no consumers are active.

> There are another consumers that committed offsets there, but they are not displayed.

This would be a bug then, please provide more information about that case. Possibly also compare it with other tools such as the Apache Kafka CLIs / shell scripts that list the group offsets. This should help to double check whether group offsets were actually committed or not.
