### ISSUE TITLE
Import monaco editor from local source again

### ISSUE THREAD

**Issue by LeoHsiao1** [redpanda-data/console#1379]
Hi!
I am using redpanda v2.7.1 and noticed that the monaco editor is not loading.
Through Chrome F12, I found out that redpanda needs to download `https://cdn.jsdelivr.net/npm/monaco-editor@0.43.0/min/vs/loader.js`, but the network times out.
Further, I found out that in 2022, Mr. @sago2k8 has import monaco editor from local source instead of a cdn. #394 
So I'm assuming that @sago2k8's work was broken by the code recently committed to redpanda.

Here's my test:
I deployed multiple versions of redpanda via docker to find out the changes:
- redpanda `v2.5.0`~`v2.5.2` import monaco editor from local source.
  ![v2 5 0](https://github.com/user-attachments/assets/f1117032-7f55-494f-86fd-bcd23f2c2a05)

- redpanda `v2.6.0`~`v2.7.1` import monaco editor from the cdn.
  ![v2 6 0](https://github.com/user-attachments/assets/ca678b94-ac7b-40d7-87f4-d7d5604895f4)

**Comment by rikimaru0345** [comment]
Thanks for reporting.
I'm looking into it.
