### ISSUE TITLE
Stream download deserialized topic data

### ISSUE THREAD

**Issue by weeco** [redpanda-data/console#145]
**Usecase**

Me as business analyst / data scientist / programmer may want to download the contents (or just a specific subset that may be filtered via javascript) of a Kafka topic. The downloaded topic data can be used for ad-hoc analysis, debugging purposes, local development etc.

The download format could be .CSV, .JSON or similar so that it's easily readible by machines/applications.

**Comment by twmb** [comment]
Closing as done with message viewer work

**Comment by twmb** [comment]
cc @bojand
