### ISSUE TITLE
Kafka messages in Protobuf do not show correctly

### ISSUE THREAD

**Issue by hongbo-miao** [redpanda-data/console#1489]
I registered the Protobuf schema in the Confluent Schema Registry:

```shell
curl --location 'https://confluent-schema-registry.internal.hongbomiao.com/subjects/production.iot.motor.proto-value/versions' \
--header 'Content-Type: application/vnd.schemaregistry.v1+json' \
--data '{
    "schemaType": "PROTOBUF",
    "schema": "syntax = \"proto3\"; package production.iot; message Motor { optional string motor_id = 1; optional string timestamp = 2; optional double temperature1 = 3; optional double temperature2 = 4; optional double temperature3 = 5; optional double temperature4 = 6; optional double temperature5 = 7; }"
}'
```

Here is my Kafka producer code: https://github.com/hongbo-miao/hongbomiao.com/tree/c60ab834456279df00ec55b1e2c7a245df82e277/hm-kafka/kafka-client/kafka-rust

I succeed connecting both AKHQ and Redpanda Console to Confluent Schema Registry.

## AKHQ

AKHQ can see the schema:

![image](https://github.com/user-attachments/assets/7c37c17c-6efe-4ec2-88c1-50370eb0a2c3)

It can also show Kafka message in Protobuf format correctly:

![image](https://github.com/user-attachments/assets/08ba6a85-6e1a-43ed-a157-2366b21a34b6)

## Redpanda Console

Redpanda Console can see the schema:

![image](https://github.com/user-attachments/assets/0b2d006e-7cfc-4713-9e2c-bcd19e59b957)

However, it cannot show Kafka message in Protobuf format correctly:

![image](https://github.com/user-attachments/assets/9affa856-214d-40c0-8ab7-3d2d4930f706)

I saw Redpanda Console support providing a git repo with proto files: https://github.com/redpanda-data/console/blob/master/docs/features/protobuf.md
However, in this case, as the proto is already in Confluent Schema Registry, so I feel it may not be neccessary.

It would be great to support this, thanks! 😊

**Comment by weeco** [comment]
Hey, did you configure the Protobuf schema registry and enabled proto?

See this docs page: https://docs.redpanda.com/current/console/config/deserialization/#sr-protobuf

**Comment by hongbo-miao** [comment]
Thank you so much @weeco ! 😃
I didn't expect there is an extra flag to enable desealizing, as it supports reading Protobuf schema from Confluent Schema Registry already.

This extra config helps me

```yaml
kafka:
  # ...
  protobuf:
    enabled: true
    schemaRegistry:
      enabled: true
      refreshInterval: 1m
```

![image](https://github.com/user-attachments/assets/039626d5-8baa-4721-8885-1e0c0ec19706)
