### ISSUE TITLE
kafka Cluster Version Mismatch in UI (Displays 3.7 Instead of 3.8)

### ISSUE THREAD

**Issue by egorgoncharenko** [redpanda-data/console#1508]
Hello,I’m experiencing an issue with Redpanda Console where the Kafka cluster version is displayed incorrectly. My Kafka cluster is running version 3.8, but the Console UI shows it as 3.7. 

Environment:

Kafka Deployment: Deployed in a Kubernetes cluster using the Strimzi operator
Kafka Version: 3.8
Redpanda Console Version:  2.7.2
![Снимок экрана от 2024-11-09 22-34-00](https://github.com/user-attachments/assets/75b61e4b-a031-4078-a6f9-37462a81ad93)
![Снимок экрана от 2024-11-09 22-35-56](https://github.com/user-attachments/assets/a1165ab9-0f5c-4396-8bf9-22c1ae024358)

**Comment by weeco** [comment]
It says at least v3.7. Newer versions can be detected as soon as they are supported by the used Kafka client. I believe the v2.8.0-beta.1 can detect up to v3.8.0. The Kafka API does not expose the exact Kafka version, hence it's a guessing mechanism. The Apache Kafka committee also ghosted a proposal on introducing the versioning repor, thus there's not much we can do besides what we already tried.
