### ISSUE TITLE
Not connect to brocker

### ISSUE THREAD

**Issue by dimonbaly** [redpanda-data/console#1544]
I launched kafka and zookeeper in my kubernetes cluster. I'm trying to connect the redpanda console to it, so that it would be convenient to manage kafka in the web version, but I get an error connecting to the broker.
It's logs
Logs(kafka/redpanda-console-deployment-74b76d85dd-59hmb:redpanda-console)[tail] ───────────────────────────────────────────────────────────────┐
│                                                                       Autoscroll:On      FullScreen:Off     Timestamps:Off     Wrap:Off                                                                       │
│ {"level":"info","msg":"config filepath is not set, proceeding with options set from env variables and flags"}                                                                                                 │
│ {"level":"info","ts":"2024-12-02T16:25:55.767Z","msg":"started Redpanda Console","version":"v2.7.2","built_at":"1725620020"}                                                                                  │
│ {"level":"info","ts":"2024-12-02T16:25:55.769Z","msg":"connecting to Kafka seed brokers, trying to fetch cluster metadata"}                                                                                   │
│ {"level":"warn","ts":"2024-12-02T16:25:55.770Z","logger":"kafka_client","msg":"unable to open connection to broker","addr":"[SASL_PLAINTEXT://kafka:9092]:9092","broker":"seed_0","err":"dial tcp: lookup SAS │
│ {"level":"warn","ts":"2024-12-02T16:25:55.770Z","msg":"Failed to test Kafka connection, going to retry in 1s","remaining_retries":5}                                                                          │
│ {"level":"info","ts":"2024-12-02T16:25:56.770Z","msg":"connecting to Kafka seed brokers, trying to fetch cluster metadata"}                                                                                   │
│ {"level":"warn","ts":"2024-12-02T16:25:56.771Z","logger":"kafka_client","msg":"unable to open connection to broker","addr":"[SASL_PLAINTEXT://kafka:9092]:9092","broker":"seed_0","err":"dial tcp: lookup SAS │
│ {"level":"warn","ts":"2024-12-02T16:25:56.771Z","msg":"Failed to test Kafka connection, going to retry in 2s","remaining_retries":4}                                                                          │
│ {"level":"info","ts":"2024-12-02T16:25:58.771Z","msg":"connecting to Kafka seed brokers, trying to fetch cluster metadata"}                                                                                   │
│ {"level":"warn","ts":"2024-12-02T16:25:58.771Z","logger":"kafka_client","msg":"unable to open connection to broker","addr":"[SASL_PLAINTEXT://kafka:9092]:9092","broker":"seed_0","err":"dial tcp: lookup SAS │
│ {"level":"warn","ts":"2024-12-02T16:25:58.771Z","msg":"Failed to test Kafka connection, going to retry in 4s","remaining_retries":3}                                                                          │
│ {"level":"info","ts":"2024-12-02T16:26:02.775Z","msg":"connecting to Kafka seed brokers, trying to fetch cluster metadata"}                                                                                   │
│ {"level":"warn","ts":"2024-12-02T16:26:02.775Z","logger":"kafka_client","msg":"unable to open connection to broker","addr":"[SASL_PLAINTEXT://kafka:9092]:9092","broker":"seed_0","err":"dial tcp: lookup SAS │
│ {"level":"warn","ts":"2024-12-02T16:26:02.775Z","msg":"Failed to test Kafka connection, going to retry in 8s","remaining_retries":2}                                                                          │
│ {"level":"info","ts":"2024-12-02T16:26:10.778Z","msg":"connecting to Kafka seed brokers, trying to fetch cluster metadata"}                                                                                   │
│ {"level":"warn","ts":"2024-12-02T16:26:10.778Z","logger":"kafka_client","msg":"unable to open connection to broker","addr":"[SASL_PLAINTEXT://kafka:9092]:9092","broker":"seed_0","err":"dial tcp: lookup SAS │
│ {"level":"warn","ts":"2024-12-02T16:26:10.778Z","msg":"Failed to test Kafka connection, going to retry in 16s","remaining_retries":1}                                                                         │
│ {"level":"fatal","ts":"2024-12-02T16:26:26.779Z","msg":"failed to create console service","error":"failed to create kafka svc: failed to test kafka connection: failed to request metadata: unable to dial: d │
│ Stream closed EOF for kafka/redpanda-console-deployment-74b76d85dd-59hmb (redpanda-console)

It's my values from my helm chart
# Redpanda Console Configuration (with SASL_PLAINTEXT authentication)
redpandaConsole:
  image: redpandadata/console:latest
  environment:
    KAFKA_BOOTSTRAP_SERVERS: "SASL_PLAINTEXT://kafka:9092"
    KAFKA_BROKER_ID: "1"
    REDPANDA_CONSOLE_SASL_USERNAME: "admin"
    REDPANDA_CONSOLE_SASL_PASSWORD: "admin-secret"
    REDPANDA_CONSOLE_SASL_MECHANISM: "PLAIN"
    REDPANDA_CONSOLE_AUTH_USERNAME: "admin"
    REDPANDA_CONSOLE_AUTH_PASSWORD: "admin-secret"
    KAFKA_BROKERS: "SASL_PLAINTEXT://kafka:9092"  # Адрес твоего Kafka брокера
    KAFKA_SASL_ENABLED: "true"  # Включение SASL
    KAFKA_SASL_USERNAME: "admin"  # Имя пользователя для SASL
    KAFKA_SASL_PASSWORD: "admin-secret"  # Пароль для SASL
  auth:
    enabled: true
    basicAuth:
      enabled: true
      username: "console-admin"
      password: "admin-password"
  ingress:
    enabled: true
    host: "kafka-ui.domen.tech"
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "1024Mi"
      cpu: "500m"
  service:
    type: ClusterIP
    port: 8080           # Порт для сервиса
    targetPort: 8080     # Порт назначения для контейнера
  persistence:
    enabled: true
    storageClassName: "yc-network-ssd"
    size: 1Gi

**Comment by weeco** [comment]
The bootstrap address is configured to `[SASL_PLAINTEXT://kafka:9092]:9092` 

it should be `kafka:9092` I assume

**Comment by dimonbaly** [comment]
> The bootstrap address is configured to `[SASL_PLAINTEXT://kafka:9092]:9092`
> 
> it should be `kafka:9092` I assume

Thank you. Yes, there was a mistake. This config works perfectly. You just need to fix the authorization.

redpandaConsole:
  image: redpandadata/console:latest
  environment:
    KAFKA_BROKERS: "kafka:9092"
    KAFKA_SASL_ENABLED: "true"  # Включение SASL
    KAFKA_SASL_MECHANISM: "PLAIN"
    KAFKA_SASL_USERNAME: "admin"  # Имя пользователя для SASL
    KAFKA_SASL_PASSWORD: "admin-secret"  # Пароль для SASL
    REDPANDA_CONSOLE_AUTH_USERNAME: "admin"
    REDPANDA_CONSOLE_AUTH_PASSWORD: "admin-secret"
  auth:
    enabled: true
    basicAuth:
      enabled: true
      username: "console-admin"
      password: "admin-password"
  ingress:
    enabled: true
    host: "kafka-ui.domen.tech"
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "1024Mi"
      cpu: "500m"
  service:
    type: ClusterIP
    port: 8080           # Порт для сервиса
    targetPort: 8080     # Порт назначения для контейнера
  persistence:
    enabled: true
    storageClassName: "network-ssd"
    size: 1Gi

**Comment by weeco** [comment]
Authentication & authorization is a Redpanda enterprise feature.
