### ISSUE TITLE
Feature request: message based access restrictions

### ISSUE THREAD

**Issue by metamarcdw** [redpanda-data/console#199]
Provide admins with the ability to filter/restrict access to specific classes of messages based on their content. 

A given cluster may hold data for many accounts/tenants within the same topic(s), and the organization which owns said cluster may be obligated to restrict access to data for certain accounts relative to location and/or jurisdiction. Suppose each message is associated with an account via it's content, using something like a header or a prefix on the key.

In order to use Kowl, this organization would require a feature that would enable them to filter whole classes of messages, based on their content, from all views for specific users or groups.

**Comment by weeco** [comment]
Got it, do you want this to be configurable in the YAML config as part of the roles config (https://github.com/cloudhut/kowl/blob/master/docs/config/kowl-business-roles.yaml)?

**Comment by metamarcdw** [comment]
Yeah that seems reasonable to me

**Comment by twmb** [comment]
This seems like something we can leverage wasm (Redpanda) for in the future, and this seems a bit complicated and niche to do generically. Closing for now unless we get another ask.

**Comment by twmb** [comment]
Also, related: https://github.com/redpanda-data/console/issues/211
