### ISSUE TITLE
Implement Cache layer

### ISSUE THREAD

**Issue by weeco** [redpanda-data/console#20]
**Use case**

Most REST endpoints actually perform multiple (sequential) requests towards Kafka. There are various reasons why a cache is beneficial for Kafka Owl.: 

- We can **reduce those endpoints' response times** by periodically prefetching some of these requests (e. g. topics list, partitionIDs and watermarks).
- By prefetching requests periodically the **load towards Kafka becomes more predictable** as we can share the responses across multiple concurrent requests (and endpoints) and distribute the requests equally over time
- A cache will potentially **save requests towards Kafka**

This feature request is prioritized low because we haven't had any performance issues with Kafka yet. The more users Kafka Owl serves, the more important this issue becomes. Even tens of developers who concurrently browse through Kafka Owl shouldn't be a problem for most Kafka clusters.

**Implementation**

We should create a storage/cache interface which allows a Redis / InMemory implementation. Additionally we'd need to add `fetchedAt` timestamps in the responses so that we can show the age of the provided data.

One of the initial ideas was to create one Cache instance for each type of data we want to cache (e. g. topics, partitions, consumer groups, ..) with the advantage that we can shift more responsibility (such as RWMutexes, MaxAge gets, generic set/get `interface{}`) towards the Cache struct.

**Comment by twmb** [comment]
Closing as franz-go caching has improved since 2019, and frontend has a cache -- can revisit if this appears necessary in benchmarks
