### ISSUE TITLE
Improve how text header values are rendered

### ISSUE THREAD

**Issue by weeco** [redpanda-data/console#207]
Currently it looks a bit weird how text values in record headers are shown. This is probably because we have support for other presentation modes (i. e. JSON). If necessary we could add some "special handling" for the common case where header values are just plain strings:

![image](https://user-images.githubusercontent.com/23424570/116917522-0d45bc80-ac4f-11eb-9ce7-09b2deb979ad.png)

**Comment by rikimaru0345** [comment]
I think for anything that doesn't contain a line-break and is below ~50 characters, the "expand" button should be hidden.

As for the actual rendering (when it is expanded): Yes it looks a bit strange, but I'm not sure what to change about it. 😂 🤷‍♂️

**Comment by twmb** [comment]
Done, will be deployed with next release
