### ISSUE TITLE
Add message count on topics list and detail

### ISSUE THREAD

**Issue by weeco** [redpanda-data/console#22]
The estimated number of messages (watermark delta) should be added on the topic list for each topic, as well as on the topic detail (at the top), which should give users a better overview.

**Comment by rikimaru0345** [comment]
Message count in detail view is done.
Showing it for all topics might be somewhat expensive though (in terms of performance)

**Comment by rikimaru0345** [comment]
For 'delete' topics: easy
For 'compact' topics: exact count would be too expensive, but we can do a few random samples in the topic to compute an average message size, then use the used disk size to get an estimation.

The main intent behind this and is to just get a rough idea, so this approach should definitely be good enough.

**Comment by twmb** [comment]
Discussed, we don't want to do this on the topic list -- very request-intensive, and still not accurate for compacted topics
We have this in topic detail
