### ISSUE TITLE
Add option to choose deserializer class in the Frontend

### ISSUE THREAD

**Issue by weeco** [redpanda-data/console#222]
To date we try to guess the right deserialization format by trying a few of the common deserializers. Things get tricky if there are topics that do not use either JSON, Avro, XML, Protobuf, MsgPack or String/Text.

For instance a long, int, short etc. This requires that users can choose a deserializer method if they want to (for the key & value indepedently). By default the method should probably remain "auto" which would just try to guess the right deserializer as we currently do.

**Comment by twmb** [comment]
Part of message viewer improvements? cc @rikimaru0345

**Comment by rikimaru0345** [comment]
No, that requires more work (including backend work)

**Comment by rikimaru0345** [comment]
This is complete, please check the video / screenshot at the end of this thread:
https://github.com/redpanda-data/console/pull/968
