### ISSUE TITLE
Feature Request: define schema (avro/proto) for a topic without schema registry

### ISSUE THREAD

**Issue by amirabiri** [redpanda-data/console#235]
Although Kowl's integration with schema registry is awesome, there is no support for cases where a topic uses a schema that was agreed between developers but without using schema registry. It's also not possible to use schema registry in such cases because of the magic bytes.

Something simple in the UI or config that allows setting the avro/proto schema of a topic explicitly will be very helpful.

**Comment by amirabiri** [comment]
OK I see that this is already supported for protobuf but not Avro ?

**Comment by weeco** [comment]
You are right. It's possible to configure protobuf deserialization either with or without schema registry (respectively with or without the "Confluent binary wrapper" as I call it).

Avro deserialization is not supported without the wrapper as of know, but adding another provider (similar to the Protobuf file & git provider) that doesn't use the binary wrapper should be trivial. I'll mark it as feature request and PRs are welcome
