### ISSUE TITLE
Mac M1: qemu segmentation fault on protobuf serialization

### ISSUE THREAD

**Issue by RiniJack** [redpanda-data/console#244]
Hi Kowl,

I'm getting this error on protobuf serialization when running in  Mac M1: 
`qemu: uncaught target signal 11 (Segmentation fault) - core dumped`

### __details:__
Image: `quay.io/cloudhut/kowl:v1.4.0`

config.yaml:
![image](https://user-images.githubusercontent.com/30981317/130604658-a50aeb4f-663d-4ea0-8f53-5dc355e3b7da.png)

Logs:
![image](https://user-images.githubusercontent.com/30981317/130604954-2c4e8d37-374b-4b00-9b03-3609543c46ea.png)

**Comment by weeco** [comment]
Hey @RiniJack ,
I'm unsure whether this is related to Protobuf or not, have you tested this?

I'm not sure whether we would need to provide a special docker image / binary for those who run it on ARM CPUs, but to date we have never worried about it. My expecation was that Docker would abstract that away, given that we use a Linux base image anyways.

**Comment by RiniJack** [comment]
Hi @weeco,
I think it is related to the Protobuf serialization, because I have been working for a while with Kowl under MAC M1 with no special issues.
Yesterday I added the Protobuf section to the config.yaml in order to view proto messages in one of the topics, and got this error. When i removed the Protobuf section from the config.yaml the error has gone (but now i can see only the binary value of the proto messages in this topic)

**Comment by weeco** [comment]
Thanks for the additional input. For proto parsing we rely on protoreflect (https://github.com/jhump/protoreflect/issues). I haven't seen a similar issue there, but I assume there's not much we could do about that the moment? :(.

**Comment by hantongliu** [comment]
Faced a similar issue.
OS - macOS big sur(11.5.2)
chip - Apple M1
docker image - quay.io/cloudhut/kowl:master
command - docker run \
  -p "8081:8080" \
  -e KAFKA_BROKERS="secret" \
  -e KAFKA_TLS_ENABLED="true" \
  -e KAFKA_SASL_ENABLED="true" \
  -e KAFKA_SASL_MECHANISM="PLAIN" \
  -e KAFKA_SASL_USERNAME="secret" \
  -e KAFKA_SASL_PASSWORD="secret" \
  quay.io/cloudhut/kowl:master

Error -
{"level":"info","msg":"config filepath is not set, proceeding with options set from env variables and flags"}
{"level":"info","ts":"2021-09-09T15:26:19.517Z","msg":"started Kowl","version":"master","git_sha":"af76fbf9d57b5492ea068efc93c46d9a7c70781d","built":"2021-09-08T18:52:25Z"}
{"level":"info","ts":"2021-09-09T15:26:19.521Z","msg":"connecting to Kafka seed brokers, trying to fetch cluster metadata"}

qemu: uncaught target signal 11 (Segmentation fault) - core dumped

**Comment by weeco** [comment]
Has anyone of you tried compiling the backend on your own? I'm unsure whether ARM64 docker hosts require a different docker image - unfortunately I'm pretty clueless about this and I don't have a M1 MacBook to reproduce :/.

**Comment by weeco** [comment]
We nowadays have Docker images and binaries that target arm64. Can anyone try these images / binaries to see if this fixes the issue? We've also updated the protoreflect library to the latest available version
