### ISSUE TITLE
Feature Request: configuration instructions for kafka connect 

### ISSUE THREAD

**Issue by cobolbaby** [redpanda-data/console#246]
https://github.com/cloudhut/kowl/blob/117dd286d2ee3fff896ec761bff3ccf5c68dd8bc/docs/config/kowl.yaml#L115-L128

> enabled: false ？ 

It seems that even if I set `enabled` to `false`, the connect menu item is still displayed. What does it mean? 

> clusters: [] 

`[]` will cause yaml file parsing to fail. `failed to parse YAML config: yaml: did not find expected key` 

> username & password

What is the purpose of the username and password configuration? Does Kafka connect interface access need to be authenticated?

**Comment by LucianWake** [comment]
Would someone be kind enough to share their kafka connect configuration?
I spent more than a day configuring it and I keep getting errors I can't seem to solve 
for example:

{"level":"fatal","msg":"failed to load config","error":"failed to parse YAML config: yaml: line 21: did not find expected key"}

And here is my config:
kafka:
  brokers:
    - data-machine:9092
  schemaRegistry:
    enabled: true
    urls: 
      - "http://192.168.40.165:8081"
connect:
  enabled: true
  clusters: 
    - name: kafka-connect-xxxx
      url: "http://192.168.40.165:8091
      tls:
        enabled: false
        caFilepath:
        certFilepath:
        keyFilepath:
        insecureSkipTlsVerify: false
      username: 
      password:
    - name: abc
      url: "http://192.168.40.165:8091
      tls: 
        enabled: false
        caFilepath:
        certFilepath:
        keyFilepath:
        insecureSkipTlsVerify: false
      username: 
      password:
