### ISSUE TITLE
Render Protobuf schema properly in Schema Registry UI

### ISSUE THREAD

**Issue by weeco** [redpanda-data/console#252]
When we introduced schema registry support for Protobuf we noticed that the JSON viewer does not work well for Protobuf schemas. We added a proper editor recently which we can use to show (and later on also edit) Protobuf schemas in the `proto3` format.

AVRO Schemas returned in JSON could also be rendered in that editor as we have syntax highlighting for JSON as well.

**Comment by twmb** [comment]
Done
