### ISSUE TITLE
reassign partitions view throws error

### ISSUE THREAD

**Issue by dobe** [redpanda-data/console#268]
when starting a reassignement (outside of kowl using kafkactl)  e.g:

```
partition=0: replicas:[107 106] addingReplicas:[106] removingReplicas:[]
```

the reassign-partitions view is shows a TypeError 

```
Cannot read properties of null (reading 'toString')
```

tested on current chrome and safari on osx 

## Stack (Decoded)

```
toString (components/pages/reassign-partitions/components/BrokerList.tsx:59:55)
map (components/pages/reassign-partitions/components/BrokerList.tsx:44:31)
allowStateChanges<T> (../../src/core/action.ts:149:15)
reactiveRender (../../src/observerClass.ts:134:28)
Array (../../src/core/derivation.ts:177:21)
isSpyEnabled (../../src/core/reaction.ts:137:23)
reactiveRender (../../src/observerClass.ts:132:8)
_allowStateChanges (../../src/observerClass.ts:145:11)
render (../../src/observerClass.ts:55:15)
```

## Environment

```
NODE_ENV : production
GIT_SHA  : 1177dfdcda669904b0fbfc54934dbeba322bf2af
GIT_REF  : v1.4.0
TIMESTAMP: 1622141499
appName  : Kowl
```

## Location

```
Protocol: http:
Path    : /reassign-partitions
Search  : 
Hash    :
```

**Comment by weeco** [comment]
Hey @dobe ,
I'm currently on vacation and hence I can not look into it in a timely fashion. However, just to make sure I'm understanding it correctly: You reassigned partition with a 3rd party tool and then tried to view the active reassignments in Kowl by browsing the "Reassign Partitions" page. 

If that's the case, could you also provide the JSON body of the response from the backend for this page? (It's a single page application that sends HTTP requests to the backend on new pages / refresh)

**Comment by twmb** [comment]
Done, for enterprise
