### ISSUE TITLE
Protobuf Git Config: BaseDirectory & Depth

### ISSUE THREAD

**Issue by MaxBoeh** [redpanda-data/console#277]
We are using the protobuf-git configuration as described at https://cloudhut.dev/docs/features/protobuf#git-repository
In our repository the proto-files live within a `proto` directory, which seems to be very common, and contains 5 levels of nested folders.

Currently KOWL searches only the first 5 levels of the checkout for `.proto` files, so our last level is not considered.

- <del>Please add a `BaseDirectory` config property within `protobuf.git.repository` config, similar to the other git-based configurations.</del> (I've overlooked, that this is already done and only the release is pending)
- Please make the `5` levels of folders searched for `.proto` files configurable.

Thank you very much!

**Comment by weeco** [comment]
Hi @MaxBoeh ,
you are right it already exists, but as far as I can see it's not yet documented.

Do you want to submit a PR for your request of making the maxDepth configurable?

**Comment by omeraha** [comment]
I'd also be glad to make the levels (depth) configurable, at least for git repositories
