### ISSUE TITLE
schema registry api: subjects needs to be urlencoded when used in a path for the schema registry API

### ISSUE THREAD

**Issue by mischac** [redpanda-data/console#311]
for schemas with references the reference has the package name (for proto schemas).
if it is not on top level the package name contains slashes, so the current call to the schema registry fails as the subject is not url encoded.

see for example from confluent kafka schema registry client
https://github.com/confluentinc/confluent-kafka-python/blob/d9a91a3d74c6447d53ba1c5733b0f99c2db2e259/src/confluent_kafka/schema_registry/schema_registry_client.py#L337

```python
        response = self._rest_client.post(
            'subjects/{}/versions'.format(_urlencode(subject_name)),
            body=request)
```

**Comment by weeco** [comment]
Fixed via the referenced PR
