### ISSUE TITLE
Feature request: Add indicator for custom configuration in topic-list

### ISSUE THREAD

**Issue by ppuschmann** [redpanda-data/console#312]
Hi,

I think it would be really helpful if we had a new column in the topic-list to indicate a topic has custom configration, like `retention.ms`.
`cleanup.policy` and `partitions` are already visible as a column, which helps a lot to identify topics that are configured in a custom way.

By adding another column, just with an indicator for custom configuration, we would improve the overview of this special configuration, especially given the case the configuration of Kafka-topics isn't managed via Terraform or other tools.

**Comment by weeco** [comment]
Hey Paul,
are you referring to the topic list where all topics are listed (url `/topics`)?

I would assume that we have to make the config settings you want to have listed there configurable then. Showing all configs from all topics that have been configured/overriden on the topic level would quickly consume too much space for many clusters I believe. So if I understand your wish correctly I believe it would be reasonable to include the topic configurations which you would like to have listed as part of the topic list. Does that make sense?

**Comment by twmb** [comment]
This might be done -- closing but we can reopen if this is found not to be done
