### ISSUE TITLE
Add an endpoint to remove all connectors for a given plugin

### ISSUE THREAD

**Issue by tomasz-sadura** [redpanda-data/console#383]
When a connector plugin gets removed from Kafka Connect, `:8083/connectors?expand=info&expand=status` call to Kafka Connect replies with `{"error_code":500,"message":"Failed to find any class that implements Connector and which name matches ... "}`, returning no connectors. It causes Redpanda Console to show fail status for the whole connect cluster and no connectors are displayed.
A new endpoint to remove all defined connectors for a given connector class will allow to unblock Redpanda Console and restore functionality of connectors management in case of connector plugin removal from Kafka Connect.

**Comment by cobolbaby** [comment]
If the request cannot return the connector list, how to delete some of them?

**Comment by tomasz-sadura** [comment]
Yes.
