### ISSUE TITLE
Config file documentation unavailable

### ISSUE THREAD

**Issue by DieterDP-ng** [redpanda-data/console#386]
It seems that the [config files](https://cloudhut.dev/docs/installation#config-files) are no longer available (due to the repo forwarding). I could find no other location where config files contents are explained unfortunately.

**Comment by weeco** [comment]
I'm sorry, here there are: https://github.com/redpanda-data/console/blob/master/docs/config/console.yaml

I will update the documentation at CloudHut as soon as possible, and we are also working on bringing the docs to redpanda.com :-).
