### ISSUE TITLE
Publish message is not working on Edge browser

### ISSUE THREAD

**Issue by ErykCh** [redpanda-data/console#387]
There is only loading editor without any possibility to insert message to send.

![image](https://user-images.githubusercontent.com/95491982/173857848-4fa41f65-2528-425a-9f8d-8f7f6ffd9d39.png)

**Comment by ErykCh** [comment]
Yes, this is a problem with access to:
https://cdn.jsdelivr.net/npm/monaco-editor@0.28.1/min/vs/loader.js

Kowl is installed on internal customer environment (security reasons) and access is only by browser on remote desktop without access to internet.

So it would be helpful if all the code was within the image and nothing was downloaded from the internet.

**Comment by weeco** [comment]
@ErykCh Agreed, we have already addressed that with https://github.com/redpanda-data/console/pull/395 , but as far as I remember some of these changes have been rolled back because of compatibility issues with the build pipeline. @sago2k8 is working on this

**Comment by sago2k8** [comment]
> @ErykCh Agreed, we have already addressed that with #395 , but as far as I remember some of these changes have been rolled back because of compatibility issues with the build pipeline. @sago2k8 is working on this.

Hey @ErykCh and @weeco, this is solved indeed, if you build master branch you can see this is already working, we are going to push a new version with all these changes soon.
