### ISSUE TITLE
Kowl Business & Redpanda

### ISSUE THREAD

**Issue by altanozlu** [redpanda-data/console#388]
Hello everyone,

We want to use Redpanda Console to analyze Redpanda cluster in our company, so we need roles because we want it to be read only. I would like to know are we going to get roles in open source Redpanda Console

**Comment by altanozlu** [comment]
@weeco

**Comment by weeco** [comment]
Hey @altanozlu ,
please reach out to your Redpanda representatives or the Redpanda sales team for the SSO & Authorization support. It is not supported as part of this open source version. I'm happy to connect you :) .

Sorry for my late response, I was on vacation.
