### ISSUE TITLE
Fix quicksearch UI/UX

### ISSUE THREAD

**Issue by weeco** [redpanda-data/console#396]
We have an inconsistent experience with regards to quick searching a table. On the topics table the quicksearch field is embedded into the table header whereas other tables such as consumer groups have an external, more present quicksearch field. We've got various user reports that they could not find the search field in the topics table anymore as it was too hidden (especially on larger displays) within the table header.

**Comment by yougotashovel** [comment]
@weeco @rikimaru0345 have you got a screenshot of this?  Would be great to include those when posting issues like this.

**Comment by rikimaru0345** [comment]
@yougotashovel 

Quick search integrated with the table:

![image](https://user-images.githubusercontent.com/28133019/175037488-ef9bbf0d-558b-4970-ba2a-0ca87162ad80.png)
![image](https://user-images.githubusercontent.com/28133019/175037537-d9a1147f-3adc-471b-8ab7-04028812a652.png)

Old quick search with separate search bar:
![image](https://user-images.githubusercontent.com/28133019/175037696-42f8b980-15f0-46a7-bad6-7d7f10a3513b.png)

**Comment by twmb** [comment]
Resolved with component migration? cc @jvorcak
