### ISSUE TITLE
problem connecting console to redpanda

### ISSUE THREAD

**Issue by hubdr** [redpanda-data/console#402]
- redpanda is installed locally (not in a docker container)
- I installed redpanda **console** in the same machine inside a container:
`docker run -d -p 8470:8080 -e KAFKA_BROKERS=192.168.1.1:9092 docker.redpanda.com/vectorized/console:master-0a8fce8` 
- However the GUI times out and the console log shows this error: `"msg":"unable to open connection to broker","source":"kafka_client","addr":"0.0.0.0:9092","broker":"1","err":"dial tcp 0.0.0.0:9092: connect: connection refused"`
- This is the relevant section from `/etc/redpanda/redpanda.yaml`:

```bash
  kafka_api:
  - address: 0.0.0.0
    port: 9092
```

- What would I need to change to be able to get the console GUI working? (keeping in mind redpanda is also being used from remote machines). Where would I add `PLAINTEXT://host.docker.internal:9092` ?

**Comment by weeco** [comment]
Hello,
this is because of how the Kafka protocol works. The brokers individually respond with advertised server addresses as part of the metadata response that clients send right after the initial connection.  If you are running on Linux you can use the `--network=host` docker option.

Both options are described in the README here: https://github.com/redpanda-data/console#redpandakafka-is-running-locally

**Comment by hubdr** [comment]
- Thanks, but it seems the command to run the console is stated incorrectly in the README. Apparently docker ignores the 
`-p 8080:8080` part when `--network=host` is also specified when bringing up the container: `WARNING: Published ports are discarded when using host network mode`
- In my case in particular, specifying the port for console to listen to is important because I have some other service running at the default port 8080.
- Would there be any workaround without the need for the console to run at 8080?

**Comment by weeco** [comment]
Hey @hubdr ,
indeed we should remove the port flag from the command, given that the ip is shared anyways. That flag does not configure what port the http server will listen on, it is just for exposing the docker container's port. So you could change the port by confguring it in Console, see: https://github.com/redpanda-data/console/blob/222b498ec0295acf0ea33888f20aa3a0440757f6/docs/config/console.yaml#L163-L164 

Then start the container in the network=host mode and you should be good. Soon we will also release a single binary for Console, which might make things easier for usecases like yours.

**Comment by hubdr** [comment]
Great! that should do it, thank you
