### ISSUE TITLE
add master tag to the newest image version

### ISSUE THREAD

**Issue by ErykCh** [redpanda-data/console#403]
Hi,
curl https://docker.redpanda.com/v2/vectorized/console/tags/list
returns a list of images, but it's hard to tell which is the most recent.

{"name":"vectorized/console","tags":["master-05ac6f1","master-0a8fce8","master-0d26c8b","master-1bd7f30","master-217260f","master-8c043bc","master-8da386a","master-920a111","master-9540d5a","master-b5b26df","master-c1e4f43","master-c8db765","master-cb51d72","master-d3baef6"]}

I would like to tag the newest image as master. To be able to pull it:  docker pull docker.redpanda.com/vectorized/console:master

**Comment by weeco** [comment]
Hey @ErykCh ,
we usually don't want to create a non-unique tag for multiple versions because in the past it came to issues when debugging user issues, because of cached images.

Please have a look at the list of available docker tags here: https://hub.docker.com/r/vectorized/console/tags
