### ISSUE TITLE
Support regex in topic protobuf mappings

### ISSUE THREAD

**Issue by upils** [redpanda-data/console#405]
For the protobuf topic mapping, we currently need to set the exact topic name.

We have a use case where our topic names are generated dynamically so we cannot give the full list in the configuration. But they all contains the same kind of message, so we would like to deserialize them all the same way.

We would like a way to give a regex in the topicName so all of our topics would match.

What do you think about this feature?

The current implementation is filling a map with the topicName as the key. https://github.com/redpanda-data/console/blob/222b498ec0295acf0ea33888f20aa3a0440757f6/backend/pkg/proto/service.go#L96

Then this map is used to check if a mapping exists for a given topic: https://github.com/redpanda-data/console/blob/222b498ec0295acf0ea33888f20aa3a0440757f6/backend/pkg/proto/service.go#L238

We could consider the topicName as a regex, try to compile it when the config is loaded (and return an error if this is invalid) and keep using the given string as the key in the map.

Then after testing if the topic given in `getMessageDescriptor()` exists in the map, we would loop on the map to check if the topic match any regex. This would be a bit slower than the current implementation.

**Comment by weeco** [comment]
Hey @upils ,
thanks for sharing your usecase. I think what you are suggesting makes sense to me. Do you want to work on this and submit a PR for this?

We should make sure that imports / nested types are supported. - regardless whether we use regexed strings or not. If I recall correctly we use protoreflect's proto registry to register all proto types in advance, but if your topics share the some proto schemas (with the same name) this should not be a problem I think.

**Comment by upils** [comment]
Thanks for the reply.

Yes I might give it a try.

I am not sure to understand what you mean about the proto registry. It might be clearer if I dive in the code.

**Comment by weeco** [comment]
I was referring to this part https://github.com/redpanda-data/console/blob/222b498ec0295acf0ea33888f20aa3a0440757f6/backend/pkg/proto/service.go#L370-L374 , but I think it's not relevant to your problem, because you are sharing the same protos across several topics and you only want to tell Console for what topics it should use the proto schemas.

**Comment by upils** [comment]
OK. Yes, I understand it should not be an issue.

**Comment by brycefisher** [comment]
I'd love to get this feature merged into master and shipped in a release. Are you still planning to work on this @upils or did you want another contributor to take over from here? No worries either way!

**Comment by bojand** [comment]
This should be addressed now via #1291.
