### ISSUE TITLE
Disable "Save Messages" Button

### ISSUE THREAD

**Issue by sw-tracker** [redpanda-data/console#407]
When viewing topics, there is a "Save Messages" button at the bottom of the screen. This is (sadly) stopping us from using kowl since being able to export all of our customer data goes against company policy.

Would it be possible to add a configuration option to disable export functionality?

**Comment by weeco** [comment]
Hey, once the data is sent from the backend to the frontend it can be saved anyways. E.g. you could just look at the browser's network tab and save the response from there as well - even in a well formatted JSON. If the user shouldn't have access to read the messages from a topic, this is something that could be configured with the Enterprise version.

We don't plan to add any access control functionality to the open source version as of today. There is an enterprise version of Console that offers access control functionality and we could possibly add a feature for this as well. If you are interested in testing the enterprise platform don't hesitate to reach out via https://redpanda.com/
