### ISSUE TITLE
Better control of max count and filters

### ISSUE THREAD

**Issue by sfrandsen** [redpanda-data/console#408]
Today the max message filter is run before other filters.

It would be great if it was possible to select if I wanted to search 500 messages for something or I wanted 500 results after filtering.

Given I want to search for a specific match of for example a order message and there is a lot of messages to search it is use less to make a filter since it will just look for the match i the first messages and probably not find any or very few.

A max time rule could also be nice to search for 1 minute for something and returning what i did find and that the time ran out (with som index details for where it stopped

**Comment by weeco** [comment]
Hi, the max results filter is always after filters. What you want to achieve is a common usecase, and to do so you just need to adapt the "Start offset" to something like "oldest" or use a timestamp from where you want to start consuming forwards. You can abort the search whenever you want then. The filter is evaluated in the backend, hence this is very fast too.

Does that help? If you use `Recent-500` as start offset it will only run the filter on all messages between `latest-500` until `latest`

**Comment by AndrewSergienko** [comment]
I want to filter messages from all messages, but if I select MAX: 500, it will apply the filter to 500 messages. How can I use the filter for all messages?

**Comment by weeco** [comment]
@AndrewSergienko You can use a different start offset, most likely you selected "Newest - 500" instead of "Oldest" or from a certain timestamp onwards.

**Comment by AndrewSergienko** [comment]
@weeco So, do I need to change start offset to process every 500 messages?

**Comment by weeco** [comment]
@AndrewSergienko If you want to process all messages like you said in your previous post - you would need to set the start offset to "Oldest" so that it starts to consume from the beginning and then processes and applies your filter on every individual records from that start offset. It will stop when it either reached the end of all partitions or when you have 500 records.

**Comment by tinmanjk** [comment]
So it will just apply a filter on a 500-batch and not the whole topic/partition?

**Comment by weeco** [comment]
> So it will just apply a filter on a 500-batch and not the whole topic/partition?

It depends on your start offset. The max results (500) is just the number of desired results you'd like to see. The search generally continues with your request until that number of results is provided or the end of all selected partitions is reached. If you want to search through an entire topic/partition use start offset: oldest (basically first message in your partition). The search will finish only if it has 500 results that pass your filter or if it has reached the end of the partition.

**Comment by tinmanjk** [comment]
@weeco I am running latest release and it's simply not the case.
There is not "Oldest" only "Beginning".
And if I start from there it will show me for example only 2 records, if I start from a later offset it will show me 10 records meaning that it is done in batches where filter is applied, not real "search".

**Comment by weeco** [comment]
Please provide more information, maybe some screenshots. We renamed oldest to beginning, sorry
