### ISSUE TITLE
Add safety-mechanism for deleting topics.

### ISSUE THREAD

**Issue by rtviii** [redpanda-data/console#413]
It's way too convenient to delete multiple adjacent topics in a row instead of writing a kafka administrator script. 

Given the speed of animation (of topics from below sliding up to replace the recently-deleted one), if there is a glitch or the person is just not accurate enough with muscle memory it is way too easy to _irrevocably_ erase an important topic, which might imply TBs of data. 

It's a gun and it needs a safety bar, pretty please.

**Comment by weeco** [comment]
There are several ways to achieve this.

1. Disable deleting topics in your target Kafka cluster
2. Provide a SASL users that is used in Console that does not have permissions to delete topics
3. Use Console Enterprise (part of Redpanda's commercial offering) to restrict delete permissions to certain users or topics.

I think our modal confirming the delete action (before actually sending a topic delete request) should prevent accidental deletions by humans though, no?

**Comment by rtviii** [comment]
Thanks for the reply @weeco! 

Yeah, wrt the confirmation modal: i don't fee like i have the upper hand with this argument, but i also can't say that i haven't deleted anything important despite it being there :'] 

The other solutions are all perfectly valid and operational, except the server-side configuriton or paying. To be fair, i _would_ definitely pay for this feature excep the cluster is not mine haha. 
But some toggle element on the topic that disables the "bin" button completely would sure be nice too.
