### ISSUE TITLE
iam configuration not working

### ISSUE THREAD

**Issue by amitca71** [redpanda-data/console#419]
i use kowl successfully with msk on kubernets (helm) using SCRAM-SHA-512 with the following configuration:
kowl:
  config:
    kafka:
      brokers:
        - ${broker1}
        - ${broker2}
        - ${broker3}
      tls:
        enabled: true
        insecureSkipTlsVerify: true
      sasl:
        enabled: true
        username: ${kafka_username}
        mechanism: SCRAM-SHA-512

When i try to use awsMskIam, the container is not being created on the kubernetes cluster with CreateContainerConfigError.
The following is the configuration i use, and the accessKey and secretKey are valid keys with appropriate authorization (works for other clients)

kowl:
  config:
    kafka:
      brokers:
        - ${broker1}
        - ${broker2}
        - ${broker3}
      tls:
        enabled: true
        insecureSkipTlsVerify: true
      sasl:
         enabled: true
         mechanism: AWS_MSK_IAM
         awsMskIam:
            accessKey: XXXXXXXX
            secretKey: XXXXXXXXXXXXX

any hint?
thanks,
Amit

**Comment by weeco** [comment]
What's the log messages / error you see? Please also enable debug logging and post them here.

**Comment by amitca71** [comment]
state:
      waiting:
        message: couldn't find key kafka-sasl-password in Secret kafka/services-secrets
        reason: CreateContainerConfigError

**Comment by weeco** [comment]
@amitca71 I assume you tried to deploy Console/Kowl with Helm? Could you please provide more information about what commands you executed? I recently added a new Helm chart, but I wasn't expecting someone to use it by now because it's fairly hidden. Thus I'm wondering what chart you are trying to use.

**Comment by amitca71** [comment]
@wecco I do use helm charts... the new chart was not working.... i set it to older version: 
  repository = "https://raw.githubusercontent.com/cloudhut/charts/master/archives"
  chart      = "kowl"
  version= "2.3.0"

btw, when i put fake value for kafka-sasl-password in the secret, the container is being created, and the error is regular error for failure: 
{"level":"warn","ts":"2022-07-21T19:42:45.017Z","msg":"Failed to test Kafka connection, going to retry in 1s","remaining_retries":5}
{"level":"info","ts":"2022-07-21T19:42:46.018Z","msg":"connecting to Kafka seed brokers, trying to fetch cluster metadata"}

**Comment by weeco** [comment]
@amitca71 I don't plan to make any changes to the existing chart anymore, but I'll make sure that the new chart will be compatible with it. Thanks for filing the issue!

**Comment by amitca71** [comment]
thanks alot!!
which version is it? can u share location?

**Comment by weeco** [comment]
@amitca71 Here: https://github.com/redpanda-data/console/tree/master/helm . Please let me know if you still have issues, then I'm happy to fix this :)

**Comment by m1mohamad** [comment]
Any updates on this ! I'm trying to configure MSK authentication using helm as here but no luck , how can I specify the iam role ? 
-------------
```
        console:
          config:
            kafka:
              brokers:
                - b-1.services-stage-clus.ccc.c9.kafka.eu-central-1.amazonaws.com:9096
                - b-2.services-stage-clus.ccc.c9.kafka.eu-central-1.amazonaws.com:9096
              clientId: redpanda-console
              sasl:
                enabled: false
                mechanism: AWS_MSK_IAM
```

**Comment by m1mohamad** [comment]
Any ideas on this guys !

**Comment by m1mohamad** [comment]
Is this option ever worked with IAM role?we are using serviceaccount that has an IAM role for argocd applications , deploying it with helm seems to 
=========
```
sasl:
  #   enabled: false
  #   username:
  #   password: # This can be set via the --kafka.sasl.password flag as well
  #   mechanism: AWS_MSK_IAM
```

Keeps failing to connect to MSK with the following error 
Internal error: SASL_AUTHENTICATION_FAILED:

When using SCRAM-SHA-12 with Secretsmanager secret it works , using awsMSKiam does not seem to work too

**Comment by contre95** [comment]
Hey, I'm struggling to understand weather `AWS_MSK_IAM` can be used at all without the need of explicitly settings parameters for `accessKey` or `secretKey` but rather using the IAM credentials that the AWS compute instance have (ECS in my case). I would like to avoid having to create an AWS IAM User just for this. All of the clients are authenticating to MSK using[ AWS IAM SALS auth method](https://docs.aws.amazon.com/msk/latest/developerguide/iam-access-control.html) therefore not having to maintain key/user rotation of any kind.
Setting the **sasl mechanisim** to `AWS_MSK_IAM` without setting the rest of the parameters doesn't seem to work, ending up in the following error: 
```json
{
  "level": "warn",
  "ts": "2023-06-30T15:24:08.505Z",
  "msg": "read from broker errored, killing connection after 0 successful responses (is SASL missing?)",
  "source": "kafka_client",
  "addr": "<broker-addr>:9098",
  "broker": "seed 0",
  "err": "EOF"
}
```
Thanks in advance for any response.

**Comment by UjjwalByjus** [comment]
> Hey, I'm struggling to understand weather `AWS_MSK_IAM` can be used at all without the need of explicitly settings parameters for `accessKey` or `secretKey` but rather using the IAM credentials that the AWS compute instance have (ECS in my case). I would like to avoid having to create an AWS IAM User just for this. All of the clients are authenticating to MSK using[ AWS IAM SALS auth method](https://docs.aws.amazon.com/msk/latest/developerguide/iam-access-control.html) therefore not having to maintain key/user rotation of any kind. Setting the **sasl mechanisim** to `AWS_MSK_IAM` without setting the rest of the parameters doesn't seem to work, ending up in the following error:
> 
> ```json
> {
>   "level": "warn",
>   "ts": "2023-06-30T15:24:08.505Z",
>   "msg": "read from broker errored, killing connection after 0 successful responses (is SASL missing?)",
>   "source": "kafka_client",
>   "addr": "<broker-addr>:9098",
>   "broker": "seed 0",
>   "err": "EOF"
> }
> ```
> 
> Thanks in advance for any response.

Hey did you find any solution?

**Comment by twmb** [comment]
We have a separate issue for env refresh, not sure what's going on in this issue.

**Comment by twmb** [comment]
(note #275 mentioned above)

**Comment by contre95** [comment]
> > Hey, I'm struggling to understand weather `AWS_MSK_IAM` can be used at all without the need of explicitly settings parameters for `accessKey` or `secretKey` but rather using the IAM credentials that the AWS compute instance have (ECS in my case). I would like to avoid having to create an AWS IAM User just for this. All of the clients are authenticating to MSK using[ AWS IAM SALS auth method](https://docs.aws.amazon.com/msk/latest/developerguide/iam-access-control.html) therefore not having to maintain key/user rotation of any kind. Setting the **sasl mechanisim** to `AWS_MSK_IAM` without setting the rest of the parameters doesn't seem to work, ending up in the following error:
> > ```
> > {
> >   "level": "warn",
> >   "ts": "2023-06-30T15:24:08.505Z",
> >   "msg": "read from broker errored, killing connection after 0 successful responses (is SASL missing?)",
> >   "source": "kafka_client",
> >   "addr": "<broker-addr>:9098",
> >   "broker": "seed 0",
> >   "err": "EOF"
> > }
> > ```
> > 
> > 
> > Thanks in advance for any response.
> 
> Hey did you find any solution?

No, this is the configuration I end up using. I could not use IAM auth with MSK and I end up use SASL username and password and store those in AWS Secret manager.


```json
  "environment": [
    {
      "value": "${aws-region}",
      "name": "AWS_REGION"
    },
    {
      "value": "${endpoints}",
      "name": "KAFKA_BROKERS"
    },
    {
      "value": "true",
      "name": "KAFKA_TLS_ENABLED"
    },
    {
      "value": "SCRAM-SHA-512",
      "name": "KAFKA_SASL_MECHANISM"
    },
    {
      "value": "true",
      "name": "KAFKA_SASL_ENABLED"
    },
    {
      "value": "true",
      "name": "KAFKA_TLS_INSECURESKIPTLSVERIFY"
    }
  ],
    "secrets": [
    {
      "valueFrom": "${pass}:password::",
      "name": "KAFKA_SASL_PASSWORD"
    },
    {
      "valueFrom": "${user}:username::",
      "name": "KAFKA_SASL_USERNAME"
    }
  ],
```

**Comment by zebesh** [comment]
I was able to launch the console with authorization via the role. What I had done:
1. OIDC provider in the EKS cluster
2. Role with rights to Kafka MSK
3. Role assigned to the service account
4. Settings passed to the Helm Chart console:
```
  extraEnv:
    - name: KAFKA_SASL_CLIENT_CALLBACK_HANDLER
      value: "software.amazon.msk.auth.iam.IAMClientCallbackHandler"
    - name: KAFKA_SASL_JAAS_CONFIG
      value: "software.amazon.msk.auth.iam.IAMLoginModule required;"
  console:
    config:
      kafka:
        clientId: redpanda-console
        sasl:
          enabled: true
          mechanism: AWS_MSK_IAM
        tls:
          enabled: true
```
