### ISSUE TITLE
Oracle Streaming Error List group and lack of information

### ISSUE THREAD

**Issue by raafael** [redpanda-data/console#420]
Hi! Has anyone facing problems with oracle streaming?

I am getting this error when list consumer Groups

``` log
{"level":"error","ts":"2022-07-21T23:03:20.319Z","msg":"Sending REST error","route":"/api/consumer-groups","method":"GET","status_code":404,"remote_address":"172.17.0.1:59712","public_error":"Failed to describe consumer groups: all '1' requests have failed, last error: UNKNOWN_SERVER_ERROR: The server experienced an unexpected error when processing the request.","error":"failed to describe consumer groups: all '1' requests have failed, last error: UNKNOWN_SERVER_ERROR: The server experienced an unexpected error when processing the request."}
```
![image](https://user-images.githubusercontent.com/5247148/180329681-21dcb0c6-cf52-4373-b55f-c0b373ea817d.png)

Something that is curious is if I click in the tab Consumers from Topic page I can see the consumers and even I can access the page with the consumer details.

And there is still a lack of information about topics like size and messages.
![image](https://user-images.githubusercontent.com/5247148/180330020-a6f216a1-7641-4562-9388-09bd4363a882.png)

I am running console with docker:

``` bash
docker run -p 9090:8080 -e KAFKA_BROKERS=broker:9092 -e KAFKA_TLS_ENABLED=true -e KAFKA_SASL_ENABLED=true -e KAFKA_SASL_USERNAME="xxxx" -e KAFKA_SASL_PASSWORD="xxxx" vectorized/console:master-8fcce39
```

**Comment by weeco** [comment]
Hey @raafael , this indicates an issue with the brokers handling the request. Please have a look at your broker logs to figure out what's going on there. There's nothing we could do on our side I think.
