### ISSUE TITLE
problem with retrieving messages

### ISSUE THREAD

**Issue by ErykCh** [redpanda-data/console#422]
Hi, I have following problem.

I have the console installed on several environments. It works fine on all but one.

On this one environment it connects, it seems that most of the functions work properly (displaying the list of topics, consumer groups, ...).

But what doesn't work is displaying messages from the topic (no matter which).

Logs (I'm trying to get messages from two topics):
{"level":"info","ts":"2022-07-26T14:29:13.858Z","msg":"started Redpanda Console","version":"master-f9ec394","built_at":"1656602044"}
{"level":"info","ts":"2022-07-26T14:29:13.858Z","msg":"connecting to Kafka seed brokers, trying to fetch cluster metadata"}
{"level":"info","ts":"2022-07-26T14:29:13.867Z","msg":"successfully connected to kafka cluster","advertised_broker_count":1,"topic_count":75,"controller_id":1,"kafka_version":"v2.6"}
{"level":"info","ts":"2022-07-26T14:29:13.867Z","msg":"creating Kafka connect HTTP clients and testing connectivity to all clusters"}
{"level":"info","ts":"2022-07-26T14:29:13.867Z","msg":"tested Kafka connect cluster connectivity","successful_clusters":0,"failed_clusters":0}
{"level":"info","ts":"2022-07-26T14:29:13.867Z","msg":"successfully create Kafka connect service"}
{"level":"info","ts":"2022-07-26T14:29:14.415Z","msg":"Server listening on address","address":"0.0.0.0:8080","port":8080}
{"level":"error","ts":"2022-07-26T14:30:33.075Z","msg":"Sending REST error","route":"/api/topics/rc.test/messages","method":"GET","status_code":400,"remote_address":"10.10.1.99","public_error":"Failed upgrade websocket","error":"failed to upgrade websocket in messages endpoint websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header"}
2022/07/26 14:30:33 http: superfluous response.WriteHeader call from github.com/cloudhut/common/rest.SendResponse (http.go:20)
2022/07/26 14:30:34 http: superfluous response.WriteHeader call from github.com/cloudhut/common/rest.SendResponse (http.go:20)
{"level":"error","ts":"2022-07-26T14:30:34.792Z","msg":"Sending REST error","route":"/api/topics/rc.test/messages","method":"GET","status_code":400,"remote_address":"10.10.1.99","public_error":"Failed upgrade websocket","error":"failed to upgrade websocket in messages endpoint websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header"}
2022/07/26 14:31:04 http: superfluous response.WriteHeader call from github.com/cloudhut/common/rest.SendResponse (http.go:20)
{"level":"error","ts":"2022-07-26T14:31:04.409Z","msg":"Sending REST error","route":"/api/topics/bs.dunning/messages","method":"GET","status_code":400,"remote_address":"10.10.1.99","public_error":"Failed upgrade websocket","error":"failed to upgrade websocket in messages endpoint websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header"}
{"level":"error","ts":"2022-07-26T14:31:06.755Z","msg":"Sending REST error","route":"/api/topics/bs.dunning/messages","method":"GET","status_code":400,"remote_address":"10.10.1.99","public_error":"Failed upgrade websocket","error":"failed to upgrade websocket in messages endpoint websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header"}
2022/07/26 14:31:06 http: superfluous response.WriteHeader call from github.com/cloudhut/common/rest.SendResponse (http.go:20)

What can I do to diagnose where the problem is?

The same version works fine in a different environment. I tested three versions on this environment and it is the same on each one.

**Comment by weeco** [comment]
Is this issue specific to one user or to the deployment?
In the past users who had issues with Websockets usually reported it was an issue with either the LoadBalancer (I think mostly AWS loadbalancers) or the ingress controller / reverse proxy which had to be configured in order to support Websockets. Other than that I don't have any pointers except for making sure that Websockets are supported in all of your components between Console and the user.

**Comment by ErykCh** [comment]
Issue is specific to the deployment.

I made a ticket here, because it seemed to me that retrieving a list of topics or consumer groups should be done with a similar architecture. And either it should all work or nothing.

But downloading messages goes through web sockets, but not the rest of the functionality?

**Comment by weeco** [comment]
@ErykCh This is correct, it always uses WebSockets for consuming messages. Reason for that is that this allows for streaming the messages (e.g. live tailing, long running searches with enabled filters which may yield a new message like every 30s etc)
