### ISSUE TITLE
docker tag master-0a8fce8 mentioned in README.md disables most function against vanilla apache kafka 

### ISSUE THREAD

**Issue by dnwe** [redpanda-data/console#423]
The README.md sample invocations reference a git sha1 of 0a8fce8 (docker.redpanda.com/vectorized/console:master-0a8fce8)

Unfortunately this is before the ApiVersions request fix was made under https://github.com/redpanda-data/console/pull/391 which means it (incorrectly) marks remote kafka clusters as running <0.8.2 kafka (because the ApiVersionsRequest is returned as invalid) and disables the consumer groups tab etc.

Looking at the available tags on the registry, I think master-65a6f6c (65a6f6c) from 2022-07-09 (22 days ago) is the latest published one. Is it worth updating the README.md to reference that snapshot which does contain the ApiVersions fix?

**Comment by weeco** [comment]
Thanks @dnwe ,
the latest tag is from yesterday `master-173596f`. I'll update this one in the README. We will be releasing a new semver tagged version very soon.

Thanks for raising the issue and explaining the usecase why this is important!

**Comment by weeco** [comment]
Pushed the markdown changes

**Comment by dnwe** [comment]
Super speedy fix on a Sunday! Thanks 😊
