### ISSUE TITLE
helm: repo not found

### ISSUE THREAD

**Issue by istar2metal** [redpanda-data/console#424]
Hello. Problem with helm repository.
I tried as described in [readme](https://github.com/redpanda-data/console/blob/master/helm/README.md)):
`helm repo add redpanda-console 'https://packages.vectorized.io/public/console/helm/charts/' 

helm repo update`

getting it:
> Error: redpanda-console chart not found in repo https://packages.vectorized.io/public/console/helm/charts/

**Comment by weeco** [comment]
Hey @istar2metal , after running what command did that error message pop up?
I just tried adding and updating the repo again and couldn't reproduce the error message.

**Comment by istar2metal** [comment]
My apologies, it's my mistake: the script had an invalid repository name "redpanda-console". With "console" working fine.
