### ISSUE TITLE
Docker image: Cannot connect to schema registry with publicly signed TLS

### ISSUE THREAD

**Issue by tmgstevens** [redpanda-data/console#427]
It seems that in the docker image, console does not pick up the default truststore: /etc/ssl/certs/ca-certificates.crt

Connectivity works when the user explicitly adds this path into the config/environment variables.

**Comment by weeco** [comment]
@tmgstevens I am not able to reproduce this behaviour. I have used Console successfully with a schema registry that uses a TLS cert signed by a commonly trusted authority (I believe LetsEncrypt in this case). Do you mind sharing the exact error messages you were seeing?
