### ISSUE TITLE
Improve wording in topic create: replication factor must be odd 

### ISSUE THREAD

**Issue by daisukebe** [redpanda-data/console#430]
Redpanda console fails to create a topic when I specify an even number for replication factor with the following message but this isn't accurate.

```
Failed to create topic, kafka responded with the following error: INVALID_REPLICATION_FACTOR: Replication factor is below 1 or larger than the number of available brokers.
```

![image](https://user-images.githubusercontent.com/350206/184586330-1800a865-1d4e-4cf2-81b9-309a239b0684.png)

Let's make the wording better as rpk does per https://github.com/redpanda-data/redpanda/commit/2eeed7658e493ebc08d19941bea17983b36080c4

**Comment by vj-codes** [comment]
@weeco hey I would like to work on this!

**Comment by weeco** [comment]
Hey @vj-codes - sounds good, I assigned you :).

**Comment by twmb** [comment]
ping @vj-codes

**Comment by rikimaru0345** [comment]
fixed in https://github.com/redpanda-data/console/pull/1166
