### ISSUE TITLE
Error to load loader.js with server.basePath

### ISSUE THREAD

**Issue by henriquelsmti** [redpanda-data/console#435]
I upgraded from kowl, and now I have an erro when try to open connect config:

`
        server: basePath: /redpanda-console
`
![image](https://user-images.githubusercontent.com/9632578/185680624-d1383f62-6730-4244-a642-4659902de68c.png)

![image](https://user-images.githubusercontent.com/9632578/185675083-c4be1c52-fe7f-4e3a-8ebf-fdabb6143bc9.png)

![image](https://user-images.githubusercontent.com/9632578/185680978-bc616b01-a914-4563-88fb-18c289b8acf1.png)

docker: docker.redpanda.com/vectorized/console:v2.0.2

**Comment by weeco** [comment]
@sago2k8 Do you have an idea?

@henriquelsmti Do you use something like URL rewrites in your reverse proxy?

**Comment by rikimaru0345** [comment]
I pushed a potential fix for this to master, let me know if that helps.

**Comment by sago2k8** [comment]
Thanks guys, yeah I think we were not serving Monaco editor from a dynamic base path 😅

**Comment by henriquelsmti** [comment]
> @sago2k8 Do you have an idea? (The title says that server.basePath is used)
> 
> @henriquelsmti Do you use something like URL rewrites in your reverse proxy?

No, only default Kubernetes nginx ingress

**Comment by sago2k8** [comment]
If that's the case @henriquelsmti main branch should work for you then, when do you think we can release this patch if it's not released already @mattschumpert ?
