### ISSUE TITLE
[Question] Configure Kafka consumer properties for Kowl

### ISSUE THREAD

**Issue by davidpiendl** [redpanda-data/console#437]
Hi,
we have auto.create.topics.enable=true in our Kafka broker. We use Kowl v1.5.0 as a Helm deployment in our K8s cluster on Azure. Due to our highly dynamic environment and internal tests we create and delete topics a lot. We observed, even if topics are deleted and no producer is active anymore, the topics get recreated. This simply happens if someone tries to consume or tries to fetch metadata for topics, which do not exist anymore. Is it somehow possible to configure the consumers in Kowl to consider [allow.auto.create.topics=false](https://kafka.apache.org/documentation/#consumerconfigs_allow.auto.create.topics) to prevent recreation?

Thanks in advance
David

**Comment by weeco** [comment]
Hey @davidpiendl ,
the kafka client used in Console already has this disabled by default and it's not possible to enable as a Console user. Thus, I think that the creation of these topics are not caused by Console.

**Comment by davidpiendl** [comment]
Hey @weeco,
I could not find the place where this is done. Could you give me a hint?

Thanks in advance

**Comment by weeco** [comment]
> I could not find the place where this is done. Could you give me a hint?

The Kafka client's default (franz-go) is disabled. It's not possible to explicitly disable this feature as we use functional options when constructing the client. The default already is auto topic creation = false (uninitialized bool inside of franz-go).

**Comment by davidpiendl** [comment]
Alright. Thank you very much.
