### ISSUE TITLE
ACL in topic/consumer group view doesn't consider prefixed ACLs

### ISSUE THREAD

**Issue by weeco** [redpanda-data/console#440]
If we have setup prefixed ACLs they do not show up in the topic or consumer group ACL view.

Explained in two images:

![image](https://user-images.githubusercontent.com/23424570/186536798-d754deb8-8b62-4d49-8924-53d1d5159949.png)

![image](https://user-images.githubusercontent.com/23424570/186536811-ea9f81dd-b95d-418d-886b-5b0a55a5835d.png)

**Comment by weeco** [comment]
Replacing the resourcePatternTypeFilter (any) with `Match` fixes the issue.

http://localhost:3000/api/acls?resourceType=Topic&resourceName=owlshop-addresses&resourcePatternTypeFilter=Match&operation=Any&permissionType=Any then returns:

```json
{"aclResources":[{"resourceType":"TOPIC","resourceName":"owlshop-","resourcePatternType":"PREFIXED","acls":[{"principal":"User:bla","host":"*","operation":"ALL","permissionType":"ALLOW"}]}],"isAuthorizerEnabled":true}
```

**Comment by sago2k8** [comment]
Thanks @weeco  there is a PR addressing this issue in the frontend.
however I have a question isn't `resourcePatterTypeFilter=Any`  a superset of `Match`?
