### ISSUE TITLE
Inconsistent order of fields in view message page

### ISSUE THREAD

**Issue by cristi-maco** [redpanda-data/console#444]
When viewing messages of a Kafka topic, the display order for the **Value** fields is inconsistent, changing randomly from message to message.
This is visible both directly on the collapsed row, as displayed in the Value column of each row, and also when expanding the row (with "+") to view the message details. 

In my Kafka topic the messages are saved in Avro format, with fields always in the same order, and other UI tools (like Kafdrop, Kafka UI) display them in a consistent order, the exact one from Kafka.

There is also no way to change the display order here. This affects usability, as it's difficult to find specific fields, or compare field values for multiple messages.

Desired behavior:
- at minimum, the Value fields should be displayed as they are on Kafka
- a better but more complex solution would be to allow custom sorting somehow (either with some button in this display page, or maybe better somewhere in a configuration/settings page, like the one where you can filter the fields displayed in the Value column for collapsed rows)

Note that this is similar, but technically a different issue from the similar ordering problem for **Header** fields, mentioned in issue #412   

![redpanda_console_message_fields_random_display_order](https://user-images.githubusercontent.com/22880903/187043264-a406293b-9634-4a01-a28a-36592407f575.png)

**Comment by cristi-maco** [comment]
Hey @weeco , 
I've checked now the docker image you mentioned, indeed the problem is fixed - the fields order is consistent now between messages, instead of random before.  
The display order is not exactly the order of fields from the message (in my avro definition), but it seems it orders the fields alphabetically by name, which is just fine, for my use case.
This new order applies to both value fields and also to key fields (I don't have any examples to check for Header fields).

So yes, from my point of view this bug is fixed, and I'm just waiting for it to make it to an official release.
Thanks.

**Comment by cristi-maco** [comment]
I've tested now this image also for some messages with headers, and the header fields are still ordered randomly (changing for same message between page refreshes) - this is not related to this task, but to #412, I just wanted to let you know.

**Comment by weeco** [comment]
Thanks for reporting back. The other issue with inconsistent header orders is still on my radar, no worries. 

Since you were the second person mentioning the avro schema field order, I opened an issue here and asked for it: https://github.com/hamba/avro/issues/209
