### ISSUE TITLE
Collapsed navigation menu - links sometimes don't work

### ISSUE THREAD

**Issue by cristi-maco** [redpanda-data/console#445]
The right-side menu can be collapsed, which is useful as it takes up less space.
But I noticed that while collapsed, **the buttons sometime don't work**, limiting utility for the user.

**Expanded**:  
- on hover: on enabled buttons, they "light up" (with no title/hint), and on disabled buttons there is a hint with details - OK
- on click (on icon, text, or anywhere inside the button): links work as expected - OK

![image](https://user-images.githubusercontent.com/22880903/187044629-cc37a70b-82bc-44f2-91ec-fda1a60df72e.png)

**Collapsed:**
- compared to Expanded the icons are smaller (they could remain bigger), and they are also not centered on the button - small UI issue, maybe it can be improved too?
- on hover: icon and button background 'lights up', hint appears - OK
- on click - if you click on the icon, the link doesn't work!  but if you click outside the icon, but still on button, the link works - **NOT OK**

![image](https://user-images.githubusercontent.com/22880903/187044336-8d088bb1-284e-4179-a594-654bfe39bf02.png)

This behavior is unexpected and misleading, and I really thought the buttons don't work at all in the collapsed menu (except for the big "R" logo button which always worked), until I was documenting the behavior when creating this issue and noticing that clicking near the icon makes to button work.

Behavior noticed on both Chrome and Firefox browsers (current versions, on Linux Debian host)

Hopefully this is a small frontend issue which is easy to fix, improving user experience.

**Comment by sago2k8** [comment]
Thanks for reporting @cristi-maco, added a PR to address this issue.

**Comment by weeco** [comment]
We push docker images between releases into a separate docker repository now. Please try this image: `vectorized/console-unstable:master-4f5baf7`

**Comment by cristi-maco** [comment]
I've just checked that image, and the reported problem is fixed now - the menu button work correctly, and the buttons also look better (with bigger icons, also centered). Thanks for fixing the problem (also including my UI suggestions)  :)
