### ISSUE TITLE
Unable to access console UI on provided port

### ISSUE THREAD

**Issue by mudassir014** [redpanda-data/console#449]
I am unable to access to console UI.
I tried running the following command as provided on the home page: 
`docker run --network=host -p 8080:8080 -e KAFKA_BROKERS=localhost:9092 docker.redpanda.com/vectorized/console:latest`
It successfully connected to my Kafka broker and I was unable to access the UI.

I then tried to change the port to `-p 808x:8080` as shown in this answer (https://stackoverflow.com/questions/71591942/unable-to-access-kowl-web-ui-running-on-docker-on-mac) but it still didn't work.
I noticed that no matter which port I provided for the console to use, it uses 8080 in all cases.

  docker run --network=host -p 8085:8080 -e KAFKA_BROKERS=localhost:9091 docker.redpanda.com/vectorized/console:latest

> WARNING: Published ports are discarded when using host network mode

{"level":"info","msg":"config filepath is not set, proceeding with options set from env variables and flags"}
{"level":"info","ts":"2022-09-01T10:49:52.296Z","msg":"started Redpanda Console","version":"v2.0.2","built_at":"1660167320"}
{"level":"info","ts":"2022-09-01T10:49:52.297Z","msg":"connecting to Kafka seed brokers, trying to fetch cluster metadata"}
{"level":"info","ts":"2022-09-01T10:49:52.324Z","msg":"successfully connected to kafka cluster","advertised_broker_count":1,"topic_count":6,"controller_id":1001,"kafka_version":"v3.2"}
{"level":"info","ts":"2022-09-01T10:49:52.324Z","msg":"creating Kafka connect HTTP clients and testing connectivity to all clusters"}
{"level":"info","ts":"2022-09-01T10:49:52.324Z","msg":"tested Kafka connect cluster connectivity","successful_clusters":0,"failed_clusters":0}
{"level":"info","ts":"2022-09-01T10:49:52.324Z","msg":"successfully create Kafka connect service"}
{"level":"info","ts":"2022-09-01T10:49:52.431Z","msg":"Server listening on address","address":"[::]:8080","port":8080}

What can I do for this work? Is there any workaround?

**Comment by weeco** [comment]
Hello,
the Redpanda Console HTTP server can be configured as part of the config. This is the config:

```yaml
server:
  listenPort: 8080
```

See the reference config here: https://docs.redpanda.com/docs/console/reference/config/

**Comment by mudassir014** [comment]
I followed it, didn't work. Same output.
I don't know what I am doing wrong.

**Comment by weeco** [comment]
@mudassir014 The logs you provided abvoe say that Console is listening on 8080, see

> {"level":"info","ts":"2022-09-01T10:49:52.431Z","msg":"Server listening on address","address":"[::]:8080","port":8080}

Is this still the case after you set these configurations?

**Comment by mudassir014** [comment]
It's not reading the config file
`{"level":"fatal","msg":"failed to load yaml config","error":"failed to parse YAML config: open config.yml: no such file or directory"}`
Even though the file is present. I tried providing relative and exclusive paths but no use.
