### ISSUE TITLE
JS error

### ISSUE THREAD

**Issue by dimaqq** [redpanda-data/console#455]
I see this in the console:

```js
Uncaught (in promise) TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
    at createForOfIteratorHelper_createForOfIteratorHelper (createForOfIteratorHelper.js:3:45)
    at normalizeAcls (backendApi.ts:1280:45)
    at backendApi.ts:627:21
```

I'm not sure if I can debug this any further.

**Comment by weeco** [comment]
Hey @dimaqq ,
could you please provide more detail? Where do you see this? In what situation do you see this?

Can you post a screenshot? Can we reproduce this? What version are you using?

My hunch based on the error message is that you are seeing this in the ACL tab. If that's the case, could you please go to the network tab when going to the ACL tab and post the JSON response that is sent by the Console backend for the ACL request?

Thank you!

**Comment by dimaqq** [comment]
http://localhost:8080/acls
the security page

docker.redpanda.com/vectorized/console                                                  latest          sha256:0da20663a723659a1ac87d8e9f1362729d56c83f2ac9f799b24d2d6bee67bb92   635338be414c   17 hours ago    140MB

**Comment by weeco** [comment]
@dimaqq Can you provide the network response for the ACL request?
