### ISSUE TITLE
Weirdly not seeing my topics

### ISSUE THREAD

**Issue by dimaqq** [redpanda-data/console#456]
I'm trying to use this tool to view a setup `postgres -> debezium -> kafka -> consumers`.

The tool shows these topics, but not my logical topics (the db table changes):

__consumer_offsets | 50 | 1 | compact | 420 B |  
-- | -- | -- | -- | -- | --
debezium-config | 1 | 1 | compact | 195 B |  
debezium-offsets | 25 | 1 | compact | 0 B |  
debezium-status | 5 | 1 | compact | 0 B |

**Comment by weeco** [comment]
@dimaqq Could you check whether these topics are discoverable with any other tools such as Kafka's CLI / shell scripts? If they are, please have a look at the backend logs. They all use the same Kafka API commands, so I think it's rather unlikely that there will be differences.

**Comment by dimaqq** [comment]
Sorry I moved on to another task.
