### ISSUE TITLE
Unable to delete a consumer group if it has no offsets

### ISSUE THREAD

**Issue by AlexeyRaga** [redpanda-data/console#458]
I have a consumer group that I see in `Console`:
<img width="867" alt="image" src="https://user-images.githubusercontent.com/1394391/190558377-7ef4abc1-9b6d-40a1-bd94-e990a3a2ab1a.png">

But I cannot delete it:
<img width="704" alt="image" src="https://user-images.githubusercontent.com/1394391/190558253-0af71de2-47fb-49fd-9d03-620a393afc81.png">

**Comment by weeco** [comment]
Can you show me the consumer group details page? A consumer group can basically only exist if it has at least one committed offset, which is why I'm surprised that you can see a group without offsets?

**Comment by AlexeyRaga** [comment]
I can't anymore. I managed to commit some offsets and then was able to delete the group.
I was also surprised seeing a group without an offset :-/

<img width="1441" alt="image" src="https://user-images.githubusercontent.com/1394391/190648991-35ad3083-70c7-4cbd-aa6f-a46241497118.png">
