### ISSUE TITLE
Schema Registry: Confluent compatibility

### ISSUE THREAD

**Issue by ffernandolima** [redpanda-data/console#468]
Hi!

I'd like to know whether the redpanda console is compatible with confluent's schema registry since I've performed some tests locally using docker and I couldn't get success on it.

Using redpanda's schema registry everything went well.

Thanks.

**Comment by weeco** [comment]
Hey @ffernandolima ,
yes it should be compatible with Confluent's schema registry. Redpanda's schema registry is also in line with the Confluent interface.

What issues did you face? Do you have any specific error logs?

**Comment by ffernandolima** [comment]
@weeco Actually, I've made it work exactly with the configuration mentioned above.

![image](https://user-images.githubusercontent.com/25134706/193141106-c5015b09-258c-4fca-b7bd-aa534b41eb8a.png)

After waiting for so long, I used the "Force Refresh" button and the "Backend API Error" went away. 

Is this huge delay expected? I ask because this delay can lead more people to think that the service is not working properly and their configurations are wrong.

Anyway, thank you.

**Comment by weeco** [comment]
@ffernandolima Have you checked whether the schema registry is reachable via HTTP when the errors popped up in Console? I think the error screen you posted is expected if the schema registry is not yet ready to serve the HTTP requests.

Console basically always just sends HTTP requests to the schema registry as they are needed, so I recommend checking whether the schema registry is actually ready to serve the HTTP responses. Checking the Console backend logs will also help to indicate why an error has happened - it would print failed HTTP requests for instance.

**Comment by ffernandolima** [comment]
@weeco I'm gonna check it out. Thanks for your support! Closing the issue for now.

**Comment by adriens** [comment]
:open_mouth: :heavy_heart_exclamation:
