### ISSUE TITLE
Missing changelog updates

### ISSUE THREAD

**Issue by philippgille** [redpanda-data/console#478]
Hello 👋 ,

Until v1.5.0, before Redpanda took over Kowl, the changelog was present in both the releases, like [here](https://github.com/redpanda-data/console/releases/tag/v1.5.0), as well as in the changelog file [here](https://github.com/redpanda-data/console/blob/v1.5.0/CHANGELOG.md). Since then, there was a major release with [v2.0.0](https://github.com/redpanda-data/console/releases/tag/v2.0.0), but no changelog in that release, and only some work in progress changelog notes in the [changelog file](https://github.com/redpanda-data/console/blob/v2.0.0/CHANGELOG.md).

It would be great if you could continue maintaining the changelog, to ease the transition from Kowl to Redpanda Console.

**Comment by weeco** [comment]
Hey @philippgille , I am sorry for that. This is on my radar. I'll update the changelog and will also maintain it for upcoming releases as soon as possible.
