### ISSUE TITLE
Using back button on topic view always resets to page 1 instead of last current page.

### ISSUE THREAD

**Issue by patrickangeles** [redpanda-data/console#482]
If you have 100s of topics, browsing through `/topics` is paginated. Clicking on a specific topic then pressing the back button always resets to page 1. Would be more useful/intuitive to go back to the same exact page as before.

**Comment by jvorcak** [comment]
Note to self, we should save pagination information to URL, that will allow us to proceed further on this.

**Comment by jvorcak** [comment]
This PR should fix this once it's merged https://github.com/redpanda-data/console/pull/1029

**Comment by twmb** [comment]
Going out with 2.4.1
