### ISSUE TITLE
Failure to verify tls certificate for schema registry

### ISSUE THREAD

**Issue by idkw** [redpanda-data/console#485]
### Version & Environment

Redpanda version: (use `rpk version`): 2.0.3
Using the docker image : 
- docker.redpanda.com/vectorized/console:latest
- sha256:635338be414cc07003a0f7d9a397c30c92f3c61e8e9b135504bb9bda28b0614b

Linux Mint Linux Mint 20.3

### What went wrong?

With this version of redpanda when using a schema registry hosted on confluent cloud (URL https://psrc-lgy7n.europe-west3.gcp.confluent.cloud/), redpanda attempts to verify the Let's Encrypt TLS certificate provided by Confluent cloud  but fails with the error : 

```
{"level":"fatal","ts":"2022-10-06T13:46:47.317Z","msg":"failed to create kafka service","error":"failed to verify connectivity to schema registry: Get \"https://psrc-lgy7n.europe-west3.gcp.confluent.cloud/subjects\": x509: certificate signed by unknown authority"}
```

However the documentation at https://docs.redpanda.com/docs/console/reference/config/#sample-configuration says : 

```
# If you connect to a schema registry that uses commonly trusted 
      # certificates, enable TLS and do not provide a certificate 
      # authority by not configuring the caFilepath. In this case, 
      # the system's cert pool is used.
```

This is false since it doesn't validate the TLS certificate properly. Redpanda seem no not know about any of the system's trusted certificates.

### What should have happened instead?

It should have trusted the host system's certificates and trusted the let's encrypt certificate provided by confluent cloud.

### How to reproduce the issue?

Start a redpanda console instance connected to a kafka cluster and schema registry on confluent cloud : 

```
docker run --name redpanda_integration -p 9001:8080 \
-e KAFKA_BROKERS=pkc-4r297.europe-west1.gcp.confluent.cloud:9092 \
-e KAFKA_TLS_ENABLED=true \
-e KAFKA_SASL_ENABLED=true \
-e KAFKA_SASL_USERNAME=xxxxx \
-e KAFKA_SASL_PASSWORD=xxxxx \
-e KAFKA_SCHEMAREGISTRY_ENABLED=true \
-e KAFKA_SCHEMAREGISTRY_TLS_ENABLED=true \
-e KAFKA_SCHEMAREGISTRY_URLS=https://psrc-lgy7n.europe-west3.gcp.confluent.cloud \
-e KAFKA_SCHEMAREGISTRY_USERNAME=xxxxx \
-e KAFKA_SCHEMAREGISTRY_PASSWORD=xxxxx \
-d \
docker.redpanda.com/vectorized/console:latest
```

My workaround currently is to mount the certiticate authority of the let's encrypt certificates used by confluent.  
On my Linux Mint host system, they ae located under /etc/ssl/certs and the authority that signs for Let's Encrypt certificates is known to be ISRG_Root_X1.

```
docker run --name redpanda_integration -p 9001:8080 \
-e KAFKA_BROKERS=pkc-4r297.europe-west1.gcp.confluent.cloud:9092 \
-e KAFKA_TLS_ENABLED=true \
-e KAFKA_SASL_ENABLED=true \
-e KAFKA_SASL_USERNAME=xxxxx \
-e KAFKA_SASL_PASSWORD=xxxxx \
-e KAFKA_SCHEMAREGISTRY_ENABLED=true \
-e KAFKA_SCHEMAREGISTRY_TLS_ENABLED=true \
-e KAFKA_SCHEMAREGISTRY_TLS_CAFILEPATH=/certs/ISRG_Root_X1.pem \
-e KAFKA_SCHEMAREGISTRY_URLS=https://psrc-lgy7n.europe-west3.gcp.confluent.cloud \
-e KAFKA_SCHEMAREGISTRY_USERNAME=xxxxx \
-e KAFKA_SCHEMAREGISTRY_PASSWORD=xxxxx \
-v /etc/ssl/certs:/certs \
-d \
docker.redpanda.com/vectorized/console:latest
```

### Additional information

Please attach any relevant logs, backtraces, or metric charts.

**Comment by idkw** [comment]
Issue being investgated via Slack
https://redpandacommunity.slack.com/archives/C039U14NY04/p1665065335747959

The issue is supposed to has been fixed in the code but not yet released, however with this image it still produces the same error

vectorized/console-unstable:master-9071a2c

```
{"level":"fatal","ts":"2022-10-06T16:44:00.016Z","msg":"failed to create kafka service","error":"failed to verify connectivity to schema registry: Get \"https://psrc-lgy7n.europe-west3.gcp.confluent.cloud/subjects\": x509: certificate signed by unknown authority"
```

**Comment by weeco** [comment]
Hey @idkw ,
we created a release candidate for v2.1.0. I was not able to reproduce your issue. Could you check whether the issue persists with this docker image `docker.redpanda.com/vectorized/console:v2.1.0-rc1` ?
