### ISSUE TITLE
Common section displayed even when empty

### ISSUE THREAD

**Issue by vladoschreiner** [redpanda-data/console#520]
When creating a new connector, the Common section gets displayed even when empty.

For the cloud connectors, config options were intentionally moved from the Common section. Yet, it is still rendered in both basic and advanced views. See the screenshots.

Reproducer: open a Create connector wizard for MirrorSourceConnector or S3SinkConnector and expand Common.

<img width="785" alt="Snímek obrazovky 2022-11-08 v 18 28 09" src="https://user-images.githubusercontent.com/16268021/200634776-ec39bdef-adaa-4954-9f20-b385040253c2.png">
<img width="776" alt="Snímek obrazovky 2022-11-08 v 18 28 16" src="https://user-images.githubusercontent.com/16268021/200634802-11b8d7c5-cddb-4a62-b53a-cda931e5b306.png">

**Comment by twmb** [comment]
Done? Closing.
