### ISSUE TITLE
Strange KAFKA_BROKERS  parsing during application startup process in K8s Env with official docker image

### ISSUE THREAD

**Issue by ZeLAxyz** [redpanda-data/console#530]
Image: vectorized/console:v2.0.3
Platform: Minikube v1.27.1
Command with normal response:
`kubectl run --namespace redpanda -i --tty --rm debug --env="KAFKA_BROKERS=kafka.confluent:29092" --image=vectorized/console:v2.0.3 --restart=Never
If you don't see a command prompt, try pressing enter.
{"level":"info","ts":"2022-11-11T07:58:10.055Z","msg":"connecting to Kafka seed brokers, trying to fetch cluster metadata"}
{"level":"warn","ts":"2022-11-11T07:58:10.057Z","msg":"unable to open connection to broker","source":"kafka_client","addr":"kafka.confluent:29092","broker":"seed 0","err":"dial tcp: lookup kafka.confluent on 10.96.0.10:53: no such host"}
`
Command with abnormal response:
`kubectl run --namespace redpanda -i --tty --rm debug --env="KAFKA_BROKERS=broker.confluent:29092" --image=vectorized/console:v2.0.3 --restart=Never
If you don't see a command prompt, try pressing enter.
{"level":"warn","ts":"2022-11-11T07:57:43.155Z","msg":"unable to open connection to broker","source":"kafka_client","addr":"broker:29092","broker":"1","err":"dial tcp: lookup broker on 10.96.0.10:53: server misbehaving"}
{"level":"warn","ts":"2022-11-11T07:57:47.154Z","msg":"unable to open connection to broker","source":"kafka_client","addr":"broker:29092","broker":"1","err":"dial tcp: lookup broker on 10.96.0.10:53: no such host"}
`

We can notice that broker address is not correctly parsed in the second command, which should be "broker.confluent:29092".

**Comment by weeco** [comment]
Hello,
the error messages indicate that the DNS was not resolvable from within the container.

Regarding the wrongly parsed Kafka brokers, could you please double check that the containers's environment variable is actually set to your expected variable by describing the pod via kubectl? If that is the case, could you provide me with a concrete example where this is happening so that I can reproduce this? Ideally with a one-line Docker command for best reproducability across our systems.

Thanks!

**Comment by ZeLAxyz** [comment]
Hello,
I have done more experiments. Here is the result:
1. I ran a docker command: 
`docker container run --rm --env KAFKA_BROKERS=broker.confluent:29092 docker.redpanda.com/vectorized/console:v2.0.3`
Then, I got the output:
`{"level":"info","msg":"config filepath is not set, proceeding with options set from env variables and flags"}
{"level":"info","ts":"2022-11-11T10:21:01.608Z","msg":"started Redpanda Console","version":"v2.0.3","built_at":"1663173158"}
{"level":"info","ts":"2022-11-11T10:21:01.608Z","msg":"connecting to Kafka seed brokers, trying to fetch cluster metadata"}
{"level":"warn","ts":"2022-11-11T10:21:01.714Z","msg":"unable to open connection to broker","source":"kafka_client","addr":"broker.confluent:29092","broker":"seed 0","err":"dial tcp: lookup broker.confluent on 8.8.4.4:53: no such host"}`
We can see that `"addr":"broker.confluent:29092"`, which is right.
2. I ran a kubectl command in Minikube v1.27.1
`kubectl run console --namespace default --image=docker.redpanda.com/vectorized/console:v2.0.3 --env="KAFKA_BROKERS=broker.confluent:29092" --attach=true --rm=true`
Then, I got the output:
'If you don't see a command prompt, try pressing enter.
{"level":"warn","ts":"2022-11-11T10:26:13.655Z","msg":"unable to open connection to broker","source":"kafka_client","addr":"broker:29092","broker":"1","err":"dial tcp: lookup broker on 10.96.0.10:53: server misbehaving"}'
We can see that `"addr":"broker:29092"`, which is wrong.
And I double checked the env in the pod with:
`kubectl exec --namespace default -i -t pods/console -- printenv`
There did exist `KAFKA_BROKERS=broker.confluent:29092`

The attached file are the dump of terminal execution. Maybe they can provide further information.
[kubectl.terminal.txt](https://github.com/redpanda-data/console/files/9989447/kubectl.terminal.txt)
[docker.terminal.txt](https://github.com/redpanda-data/console/files/9989457/docker.terminal.txt)

**Comment by weeco** [comment]
@ZeLAxyz I think what you see in the logs there is the address that was reported as part of the reported advertised.listeners. Are you familiar with the concept of the advertised listeners in Kafka?

Closing this issue as it's not an issue with Console
