### ISSUE TITLE
Is Reassign Partitons enterprise-only?

### ISSUE THREAD

**Issue by piotrp** [redpanda-data/console#546]
I was checking out how Redpanda Console would work on my Kafka cluster, and found out that Reassign Partitions in not available in free version:
![obraz](https://user-images.githubusercontent.com/1409807/202547046-1f440fb7-0971-4b54-8759-fbb655b603e4.png)

Do you have a list of enterprise-only features?

**Comment by weeco** [comment]
Hey @piotrp ,
yes this feature is an enterprise only feature. Other enterprise features are Authentication, Authorization (RBAC) and audit logging. Console enterprise is only available as part of the Redpanda platform offering. If you are interested in it you can get a trial here: https://redpanda.com/try-redpanda
