### ISSUE TITLE
Topic statistics bar: customization doesn't work

### ISSUE THREAD

**Issue by rikimaru0345** [redpanda-data/console#55]
Adding/removing configuration entries in the top bar of a topic is not saved correctly.

https://github.com/cloudhut/kowl/pull/27 tried to add "intelligent defaults" (determining what properties are shown **by default** (meaning when no setting exists yet)) but it partially caused this issue. The idea is good, but it needs to be reworked completely.

- When a user views a topic for the **first time**, kowl should calculate what configuration-properties make sense, and set/save that so it isn't recomputed the next time he visits (even if he makes no changes: doesn't add/remove any properties)

**Comment by rikimaru0345** [comment]
will be done later, not for 1.1.

**Comment by twmb** [comment]
This was removed, no longer relevant
