### ISSUE TITLE
messages not loading in the UI

### ISSUE THREAD

**Issue by Aravindjeev** [redpanda-data/console#553]
I have redpanda-console running in my kubernetes cluster through helm-chart .i have added my kafka configuration and i'm able to see my topic in the console UI but the messages are not loading.

<img width="1181" alt="Screenshot 2022-11-24 at 12 53 24 PM" src="https://user-images.githubusercontent.com/40687067/203719212-17d7ce50-07f9-4e3c-87a7-44c965aa7e93.png">

i checked into the pod logs , it gave below logs with error:

{"level":"error","ts":"2022-11-24T06:18:30.820Z","msg":"Sending REST error","route":"/api/topics/SOCKET_POINTER/messages","method":"GET","status_code":400,"remote_address":"172.XX.XX.XXX","public_error":"Failed upgrade websocket","error":"failed to upgrade websocket in messages endpoint websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header"}

I have nginx ingress controller setup in my K8s cluster with loadbalancer type = ALB and Kafka is deployed in the cluster with 3 brokers exposed as ingress service .

Please help me with this issue .

**Comment by Aravindjeev** [comment]
Fixed this issue by adding this annotations in my ingress.yaml in the redpanda deployment.
```
annotations:
  nginx.org/websocket-services: "<Service-Name>"
```

**Comment by BBQigniter** [comment]
in case anyone else finds this issue

after upgrading to v2.2.2 we stumbled into this problem because of the recently added `server.allowedorigins` config introduced in v2.2.0. We use `ingress-nginx` where the annotation mentioned in previous comment does not exist - but we fixed it via setting following `env`-variable in the corresponding Kubernetes-manifest

```
...
    env:
    - name: SERVER_ALLOWEDORIGINS
      value: "http://internal-domain.example.com,https://external-domain.example.com"
...
```
