### ISSUE TITLE
Consumer Groups with '#' character in their name cannot be inspected

### ISSUE THREAD

**Issue by Dugong42** [redpanda-data/console#555]
### Summary

I have a consumer group with the '#' characters in its name : `consumer_group_prefix_#sometext`
Console fails to properly fetch its information when loading the detail page of the group.

### What I observed

In the "Consumer Group" tab, I see a group named `somename_#foo`

If I click on the group, I get a page with the following error messages :

> Backend API Error
> Something went wrong while pulling data from the backend server
>
> Requested group id 'somename_' does not exist in Kafka cluster

The call to the API fails with status `404` :
`GET | https://<hostname>/api/consumer-groups/somename_`
`{"statusCode":404,"message":"Requested group id 'somename_' does not exist in Kafka cluster"}`

### What I expected

Console should support the full characters set allowed by Kafka for its group-ids

### Steps to reproduce

1. Create a consumer group with '#' in its name.
2. Navigate to the "Consumer Groups" tab in Console.
3. See that the group is created
4. Click to open the consumer group's details
5. Loading the consumer group fails

**Comment by weeco** [comment]
This has been fixed and is part of the latest Console release.
