### ISSUE TITLE
Provide more context in error messages

### ISSUE THREAD

**Issue by JakeSCahill** [redpanda-data/console#557]
If the `redpanda.adminAPI.urls` field is empty, Redpanda Console throws this error:

```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/redpanda-data/console/backend/pkg/redpanda.NewService({{0x1, {0x0, 0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, {0x0, ...}, ...}}}, ...)
	/go/pkg/mod/github.com/redpanda-data/console/backend@v0.0.0-20220810143308-dc4e1eaccd53/pkg/redpanda/service.go:44 +0x750
github.com/redpanda-data/console/backend/pkg/api.New(0xc000405600, {0xc0005bf2a0, 0x1, 0x8?})
	/go/pkg/mod/github.com/redpanda-data/console/backend@v0.0.0-20220810143308-dc4e1eaccd53/pkg/api/api.go:60 +0x425
main.main()
	/app/cmd/main.go:67 +0xc85
```

It would be nice to try to catch this and provide the user with more context.

**Comment by weeco** [comment]
Thanks @JakeSCahill ,
the new error msg will be:

> {"level":"fatal","msg":"failed to validate config","error":"failed to validate Redpanda config: failed to validate admin api config: you must specify at least one URL"}

If you have redpanda admin api enabled but no URL specified.
