### ISSUE TITLE
option to disable telemetry

### ISSUE THREAD

**Issue by morriswinkler** [redpanda-data/console#577]
Is it possible to add an option to disable the telemetry send to `https://m.rp.vectorized.io/telemetry`.

I think you also should add something about that in the documentation. 

You might also want to remove the visualstudio code dev server from your prod container `docker.redpanda.com/vectorized/console`, there are also secrets emebedded in that container. 
Are you building those images from a developer machine ?

All in all I have to say your software doesn't look like something you would want to setup into a production environment.

Maybe you just publish your dockerimages from this repo, would be easier to review and give people some trust in your project. 
If you want to make money from licenses just require professional businesses to pay a license. Otherwise why don't you make the whole project closed source. It makes little sense to have part of the source code reviewable while it is unclear what is build into a production image.

**Comment by emaxerrno** [comment]
howdy! 

> quick note, in the future, please use numbers so we can refer to questions in detail

1. yes use `analytics.enabled: false` check the release notes
2. the secret is not really a secret, just a signature for the purpose of preventing spam on the telemetry to tell us which features users use. not really a protection, just basic cleanliness of the API. 
3. good question, of course not built on a dev machine. These are all built as part of the redpanda pipelines, everything is reproducible and hermetic. for example, for upstream redpanda we compile llvm to compile the libs to compile redpanda
4. fortune 500 depend on this software. but no need to use if you dont' feel comfy. 
5. you are welcomed to build the project on your own. we build _one_ pipeline, mostly on resources. that pipeline is the combined result of a ton of features that are up and coming. you can type go build on your own, and do the full release of the base features on your own no problem. 
6. licensing is exactly as you described. console is part of the redpanda platform. it is a full platform includes redpanda, console, rpk, k8s operator, helm charts, etc, etc.  so it is already as you would expect. console is not a separate product, it is all one product. you are welcome to use the free version on your own as long as you feel comfortable.
