### ISSUE TITLE
is there a way to block the UI actions of "Create Topic", "Publish Message" and "Delete Records"?

### ISSUE THREAD

**Issue by cyberjar09** [redpanda-data/console#588]
I cannot use this tool in production unless the redpanda console is "read-only".
this means the UI actions like "Create Topic", "Publish Message" and "Delete Records" need to be blocked

is this possible?

**Comment by weeco** [comment]
Yes it's possible as part of the Enterprise version which can be unlocked as part of Redpanda Platform.
