### ISSUE TITLE
Consumer Groups shows negative LAG as 0 

### ISSUE THREAD

**Issue by jason-da-redpanda** [redpanda-data/console#590]
A negative LAG can occur when MM2 source/checkpoint connector is running ... and it is something we want to monitor when migration from one RP instance to another ..

Currently Console shows '0' in the case of a negative lag value .  

Can we change it so it shows the true value please

![Screenshot 2023-01-05 at 13 45 00](https://user-images.githubusercontent.com/114514850/210794854-35767cc8-ed46-4fda-8725-d2be917272c1.png)

![Screenshot 2023-01-05 at 13 44 31](https://user-images.githubusercontent.com/114514850/210794928-c385b6ae-0bc2-400e-a762-a12ba7a58846.png)

**Comment by weeco** [comment]
@jason-da-redpanda or @tomasz-sadura Can you explain why it is a negative lag? What is a positive lag in that case then?

**Comment by tomasz-sadura** [comment]
Positive lag is just a lag. lag = 100 means the consumer is 100 messages behind.
Negative lag occurred during MM2 migration tests. The consumer group offsets were migrated instantly, while the topic messages took some time to replicate. For the whole replication time, CG offsets were higher that the log end offsets, which caused negative lag.

**Comment by weeco** [comment]
I think I'm tending towards not fixing this. Interpreting negative lag as zero was made for a reason for the majority of the cases when there is a slight negative offset expected due the time diff between describing the high water marks and the consumer group offsets.

I think in regards to monitoring the MM2 migration process we are still better of when relying on Prometheus metrics right @tomasz-sadura ?

**Comment by tomasz-sadura** [comment]
Yes, I think so. Let's ask @jason-da-redpanda who did tons of migrations already.
