### ISSUE TITLE
users/role KOWL

### ISSUE THREAD

**Issue by onacht** [redpanda-data/console#593]
is the any support or concept of users or authorization in KOWL?

**Comment by weeco** [comment]
Kowl has been acquired by Redpanda. The enterprise version which comes with Redpanda Enterprise has support for authentication & authorization with an RBAC model that integrates nicely with GitHub, Okta, Google etc.

See here: https://docs.redpanda.com/docs/platform/console/single-sign-on/authorization/

**Comment by onacht** [comment]
thank you very much
