### ISSUE TITLE
context deadline exceeded with IAM

### ISSUE THREAD

**Issue by amitca71** [redpanda-data/console#609]
Hi,
I use the latest docker-compose, using aws iam.
....
        tls:
             enabled: true
             insecureSkipTlsVerify: true
           sasl:
             enabled: true
             mechanism: AWS_MSK_IAM
             awsMskIam:
                accessKey: xxxx
                secretKey: xxxx
                sessionToken: xxxx
as can be seen in the log, the client authenticates, and then fails (the user has full admin on AWS)

console_1  | {"level":"debug","ts":"2023-02-02T17:51:15.684Z","msg":"sasl has a limited lifetime","source":"kafka_client","broker":"seed 0","reauthenticate_in":37689.904}
console_1  | {"level":"debug","ts":"2023-02-02T17:51:15.684Z","msg":"connection initialized successfully","source":"kafka_client","addr":"b-2.xxxxt-2.amazonaws.com:9098","broker":"seed 0"}
console_1  | {"level":"debug","ts":"2023-02-02T17:51:15.684Z","msg":"wrote Metadata v9","source":"kafka_client","broker":"seed 0","bytes_written":36,"write_wait":0.9619081,"time_to_write":0.0001466,"err":null}
console_1  | {"level":"debug","ts":"2023-02-02T17:51:18.670Z","msg":"read Metadata v9","source":"kafka_client","broker":"seed 0","bytes_read":0,"read_wait":0.0002975,"time_to_read":2.9860352,"err":"context deadline exceeded"}
console_1  | {"level":"debug","ts":"2023-02-02T17:51:18.671Z","msg":"read from broker errored, killing connection","source":"kafka_client","addr":"xxxx2.amazonaws.com:9098","broker":"seed 0","successful_reads":0,"err":"context deadline exceeded"}
console_1  | {"level":"debug","ts":"2023-02-02T17:51:18.671Z","msg":"kafka broker disconnected","source":"kafka_client_hooks","host":"xxxxamazonaws.com"}
console_1  | {"level":"debug","ts":"2023-02-02T17:51:18.671Z","msg":"retrying request","source":"kafka_client","tries":2,"backoff":0.503233611,"request_error":"context deadline exceeded","response_error":"context deadline exceeded"}
console_1  | {"level":"warn","ts":"2023-02-02T17:51:18.671Z","msg":"Failed to test Kafka connection, going to retry in 16s","remaining_retries":1}
console_1  | {"level":"fatal","ts":"2023-02-02T17:51:34.642Z","msg":"failed to create kafka service","error":"failed to test kafka connection: failed to request metadata: context deadline exceeded"}

**Comment by twmb** [comment]
This would be due to broker dial / connection timeout. Can you try adjusting that? Closing for now.
