### ISSUE TITLE
Authentication for web ui

### ISSUE THREAD

**Issue by arezvani** [redpanda-data/console#617]
Hi,
How can I have set authentication with user and pass for redpanda console. 
Please help me, I really need that.

**Comment by weeco** [comment]
Hey @arezvani ,
authentication & authorization is part of Redpanda Enterprise. Console already supports these features, which you can unlock with an enterprise license. You can get a free 30-day trial here: https://redpanda.com/try-redpanda?section=enterprise-trial or you can also talk to the Redpanda sales team.
