### ISSUE TITLE
Self Signed Cert: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by apatelWU** [redpanda-data/console#621]
Running in local Kubernetes with self signed certificate.
Getting following error:
`21:00:07.433 [DEBUG] opening connection to broker; addr: redpanda-0.redpanda.redpanda.svc.cluster.local.:9093, broker: seed 0
21:00:07.442 [WARN] unable to open connection to broker; addr: redpanda-0.redpanda.redpanda.svc.cluster.local.:9093, broker: seed 0, err: x509: certificate signed by unknown authority
unable to request metadata: unable to dial: x509: certificate signed by unknown authority`

**Comment by weeco** [comment]
@apatelWU , could you please try to connect with another application such as rpk or kcl to your brokers with the same CA? This code hasn't changed for a while and I have also tested this successfully with a self-signed CA in the past, hence I'm currently suspecting the CA itself being the culprit.
