### ISSUE TITLE
Browser freezes when json is large

### ISSUE THREAD

**Issue by maxm86545** [redpanda-data/console#627]
I want to see the details of the message (Headers, Compression, Transactional and so on) but when opening a large json (1+ million elements) my browser freezes.

<img width="501" alt="image" src="https://user-images.githubusercontent.com/49632507/219611306-00985d74-1c68-4bfb-b58a-dbf4a7f19b09.png">

**Suggestion:** For large json, don't parse on open, add a message "message is too large" and a button to parse json on demand.

**Comment by weeco** [comment]
Hey @maxm86545 , makes sense to me. Thanks for reporting. Probably we should not send the message to the frontend at all in case it's that large.

**Comment by weeco** [comment]
Was just able to reproduce this with way smaller messages such as 85kb value payload:

![ss-YCpjQpL7@2x](https://github.com/redpanda-data/console/assets/23424570/7b19d4dc-63fe-40c5-8e8d-945a82db0432)
