### ISSUE TITLE
Regression while updating from v2.1.1 to v2.2.0

### ISSUE THREAD

**Issue by OuesFa** [redpanda-data/console#634]
I'm currently evaluating Redpanda Console for a test Kafka cluster. I tested an update from version 2.1.1 to version 2.2.0, but the new pod started crash-looping with the error message below.
Just to provide some additional information, I'm deploying the app using the kowl chart from https://github.com/cloudhut/charts . Also, the vectorized/console image is pulled from docker.redpanda.com.
I'm connecting the Kowl instance to a plaintext Kafka listener with no authentication required, BTW.
```
flag provided but not defined: -kafka.tls.passphrase
Usage of ./console:
  -config.filepath string
    	Path to the config file
  -kafka.protobuf.git.basic-auth.password string
    	Basic Auth password
  -kafka.protobuf.git.ssh.passphrase string
    	Passphrase to decrypt private key
  -kafka.protobuf.git.ssh.private-key string
    	Private key for Git authentication
  -kafka.sasl.aws-msk-iam.secret-key string
    	IAM Account secret key
  -kafka.sasl.aws-msk-iam.session-token string
    	Optional session token for authentication purposes. Uses the AWS Security Token Service API
  -kafka.sasl.gssapi.password string
    	Kerberos password if auth type user auth is used
  -kafka.sasl.oauth.token string
    	OAuth Bearer Token
  -kafka.sasl.password string
    	SASL password
  -login.github.client-secret string
    	Oauth clientSecret
  -login.github.directory.personal-access-token string
    	Personal access token to list members from Organizations and Teams
  -login.google.client-secret string
    	Oauth clientSecret
  -login.jwt-secret string
    	A random string of (at least) 64 characters, that will be used as a signing key for login JWTs. Changes will invalidate previous logins!
  -login.oidc.client-secret string
    	Oauth clientSecret
  -login.okta.client-secret string
    	Oauth clientSecret
  -login.okta.directory.api-token string
    	API token to resolve Okta group memberships
  -metrics.prometheus.basic-auth.password string
    	Basic Auth password for Prometheus endpoint
  -owl.topic-documentation.git.basic-auth.password string
    	Basic Auth password
  -owl.topic-documentation.git.ssh.passphrase string
    	Passphrase to decrypt private key
  -owl.topic-documentation.git.ssh.private-key string
    	Private key for Git authentication
  -schema.registry.password string
    	Password for authenticating against the schema registry (optional)
  -schema.registry.token string
    	Bearer token for authenticating against the schema registry (optional)
```

**Comment by weeco** [comment]
Hey @OuesFa , we have deprecated the kafka tls passphrase option because it's insecure by design and we want to discourage our users to use this. From the changelog for v2.2.0:

> [CHANGE] We removed the support for using encrypted PEM certificates as specified in RFC 1423 because it's insecure by design and should not be used by anyone

https://github.com/redpanda-data/console/blob/master/CHANGELOG.md

Sorry if this causing trouble for you, but we made the decision to remove this option without cutting a major release because it's insecure and also deprecated in Go for the same reason.

**Comment by OuesFa** [comment]
Thanks, @weeco, for your quick answer. I get it that the config is outdated, but I'm currently using an unsecured Kafka test cluster with a plain text listener, which means I haven't set up any authentication or encryption in the Helm Release values. So, why am I still getting this error? 🤔

**Comment by weeco** [comment]
Ooh I get it @OuesFa ,
this charts repo is very outdated - I'll add a hint in the README there now. The charts were migrated ~2 years ago to this one https://github.com/redpanda-data/console/tree/master/helm and a few months ago then to https://github.com/redpanda-data/helm-charts where it is maintained by another team.

Could you try migrating to this chart repo? The chart values shouldn't be too different, depending on what version you are coming from.
