### ISSUE TITLE
How can I disable the license expiration warning?

### ISSUE THREAD

**Issue by ErykCh** [redpanda-data/console#644]
I've never had an enterprise license.
After installing version 2.2.1 I get this message. I don't see any way to turn it off.

![image](https://user-images.githubusercontent.com/95491982/222725985-dca9e1aa-c204-447d-ac09-8681ea69ff02.png)

**Comment by weeco** [comment]
Hey @ErykCh ,
this must be a bug, thanks for reaching out. I assume you have not set a Redpanda license for Console at all right?

**Comment by freef4ll** [comment]
Also seeing this, no license is set.

Simple Docker container which has the following environment variables set:
```
SERVER_LISTENPORT
KAFKA_BROKERS
```

**Comment by weeco** [comment]
Hey @ErykCh ,
can you test this docker img and see if the error is gone? `redpandadata/console-unstable:release-2.2-8d74469`

**Comment by ErykCh** [comment]
> I assume you have not set a Redpanda license for Console at all right?

no

**Comment by ErykCh** [comment]
> can you test this docker img and see if the error is gone? 

the message is no longer shown in this image

**Comment by freef4ll** [comment]
Looks good, thank you!

**Comment by weeco** [comment]
Thank you both for verifying. Here's the patch release that contains the fix: https://github.com/redpanda-data/console/releases/tag/v2.2.2
