### ISSUE TITLE
Real-time update of topic messages

### ISSUE THREAD

**Issue by apetrichkovich** [redpanda-data/console#656]
Hello.
I've an issue with Console 2.2.2 in Docker.

Steps:
I've opened some topic and monitoring for new messages.
I just refresh my app page and it sends messages, but looking how topic page of Console is working I can see that it sends HTTP (AJAX) requests every 5 seconds.
But even so it is updating just mesages number, but not updates messages list what is very strange.

Expected:
It should use Websocket that update messages number and messages list at the moment new messages are available.

**Comment by weeco** [comment]
Hi,
this is currently by design. If you want to receive message live, please set start offset to latest and you'll receive new messages as they arrive until the number of maximum messages is received. Does that help?

**Comment by apetrichkovich** [comment]
Hi.
Thank you for your response.
**Yes, it is better** - now I see new messages without refreshing page and without clicking refresh button.
But there can be small bugs with starting/stopping real-time listening: I had a case when I it is not possible to start real-time listening without selecting some option even if it is already showing on the page (can't to reproduce it again).
It should be tested by QA cause it is possible I understand wrong the concept how does it work.

**Comment by weeco** [comment]
The message search is probably the most tested and used function within Console and so far we haven't seen any issues with that. Please let us know if you have more concrete information for the transient issue you were seeing then I'll reopen this issue
