### ISSUE TITLE
Differentiate null and empty string as keys in UI

### ISSUE THREAD

**Issue by kichel98** [redpanda-data/console#660]
### Version
```
Kowl CI
v1.5.0-598117c
(built November 10, 2021)
```
Unfortunately I cannot test it on the latest release, maybe it is already fixed, I don't know.

### Problem
Producing messages with `key=null` (no key) and with `key=""` leads to the same view in UI:
![image](https://user-images.githubusercontent.com/44356453/227182701-40af9152-6320-4c8f-bf02-675a973b9f18.png)

But `kafka-console-consumer` with `--property print.key=true` differentiates these two situations:
- for null key it is:
```
null    <msg1>
null    <msg2>
...
```
- for "" key it is:
```
        <msg1>
        <msg2>
...
```

This fix could help me a lot in debugging problems with assigning messages to partitions: messages with null key are usually uniformly distributed to partitions but messages with `""` key always go to one partition.

**Comment by weeco** [comment]
Hey @kichel98 ,
your request makes sense to me and I agree we should differentiate between these two cases. I'm thinking of how to do this visually, I'll ask @mo-redpanda for input.
