### ISSUE TITLE
Console startup for connecting to kafka port should have configurable retry count

### ISSUE THREAD

**Issue by hcoyote** [redpanda-data/console#663]
https://github.com/redpanda-data/console/blob/772a513710b00c7bd9fab1cf0a3fd4e4f3189b63/backend/pkg/kafka/service.go#L65-L77

This appears to be hardcoded to attempt up to 5 times. With the exponential backoff, if a cluster or set of pods are not ready within 1+2+4+8+16 seconds, you end up with a failed console startup attempt. The number of retries should be configurable. I think the 15 second connection timeout to the kafka port is probably not providing any appreciable time on this as well. If the redpanda broker host (or pod) is up and pingable, but the port is not listening, you'll get a tcp reset immediately, which will fastfail the connection attempt.

May also want to cap the exponential backoff so after it hits something like 30 or 60 seconds, it just continues to retry every period thereafter, otherwise you quickly get to a point where console backs off so long that it won't retry in a timely fashion.

**Comment by hcoyote** [comment]
To be clear: the console startup should have a configurable retry setting to allow console to attempt to hit the RP server's kafka port during startup before failing out. In a k8s setup, this causes the console pod to fail out pretty quickly if the RP pods aren't fully bootstrapped yet, throwing unnecessary errors to the end user.

**Comment by cirego** [comment]
Thanks @hcoyote, this would be a much appreciated enhancement!

**Comment by weeco** [comment]
Filed PR: https://github.com/redpanda-data/console/pull/664
