### ISSUE TITLE
How do I increase timeout? Time out due to server being far away (another region) - unable to open connection to broker

### ISSUE THREAD

**Issue by srobles-iress** [redpanda-data/console#714]
Here is log from docker: 
![image](https://github.com/redpanda-data/console/assets/109507394/e326cd31-bb35-4fa5-b23f-df151e00dba8)

Whenever I send a message to kafka to this server, I usually add a few seconds for timeout, but not sure how I can increase timeout here in this docker redpanda console... Here is my docker-compose config:

redpanda:
      image: docker.redpanda.com/vectorized/console:v2.2.3
      container_name: redpanda-${SITE}
      networks:
        - tangle
      ports:
        - ${SERVER_LISTENPORT}:${SERVER_LISTENPORT}
        - 9094:9094
      env_file: .env
      volumes:
        - .\ssl:/d
      restart: always

Please note I have to use company VPN otherwise I won't be able to connect. The company VPN is very slow on my region
I gave the exact same code to two other people and they aren't timing out (probably nearer the region?)

**Comment by weeco** [comment]
This looks like a DNS timeout issue, where it takes >10s to resolve a DNS entry. I think the timeout is currently hardcoded, but given that the DNS lookup already fails (very few bytes), I'm afraid you wouldn't be able to initiate the Kafka connection anyways with a larger timeout.
