### ISSUE TITLE
[v2.3.0] Missing field in update connector config

### ISSUE THREAD

**Issue by nvlong198** [redpanda-data/console#715]
### Version & Environment

Redpanda version: (use [v2.3.0] ):

### What went wrong?
missing these fields in the config editor:
```
key.converter.apicurio.registry.auto-register
key.converter.apicurio.registry.find-latest
key.converter.apicurio.registry.url
```

![image](https://github.com/redpanda-data/redpanda/assets/23328191/99c6de2b-1687-4965-96ae-b95a79d2f525)

### How to reproduce the issue?

1. Edit connector contains existing `key.converter.apicurio.*` configuration
2. Update button
3. Updated connector does not contain `key.converter.apicurio.*` in the configuration

### Additional information
caused this error
![image](https://github.com/redpanda-data/redpanda/assets/23328191/e895a30e-6dd1-4180-93f5-a02bf7f31186)

**Comment by weeco** [comment]
Hey @nvlong198 ,
you are right that Console only supports schema registry that are compatible with the interface that has been documented by Confluent. I think your screenshots indicate that this is indeed not v2.3.0 (as indicated via the issue title). We have re-worked the expeirence entirely there and I wonder whether the issue persists there as well and if it does if it's different.

**Comment by nvlong198** [comment]
@weeco how I can config these fields from the UI? I not find any placeholder for them.
```
value.converter.apicurio.registry.auto-register
value.converter.apicurio.registry.find-latest
value.converter.apicurio.registry.url
key.converter.apicurio.registry.auto-register
key.converter.apicurio.registry.find-latest
key.converter.apicurio.registry.url
```

**Comment by weeco** [comment]
What connector are you using? We've made the experience simpler to use by making the setup wizard more opinionated - at the cost of flexibility. I'm not sure if we have any plans supporting other schema registries such as apicurio if they are incompatible with the more commonly known schema registry interface. I'm not sure if Console will be the right tool for you to manage your connectors in that case, but I'll flag it with the Console pm.

**Comment by nvlong198** [comment]
I using Oracle connector,
if you don't have any plans to support, I will use the old UI config in v2.1.1

**Comment by weeco** [comment]
I think you should be able to add these fields when you create a connector. As of today there's no JSON editor when you want to edit these connectors, but we plan to bring this JSON editor back so that you can also edit your custom configurations (that aren't part of the form wizard) when editing the connectors. Would that help you?

**Comment by nvlong198** [comment]
I'm sure it will help me a lot, thanks.

**Comment by brycefisher** [comment]
@weeco is there an open PR for the JSON editor or would you accept a PR to bring this functionality back?

**Comment by weeco** [comment]
@brycefisher The JSON editor has already been reintroduced - it's on the master branch and not part of the 2.3 release
