### ISSUE TITLE
Connector configuration removed on update

### ISSUE THREAD

**Issue by jrkinley** [redpanda-data/console#717]
Not all of the S3 Sink connector properties are exposed in the setup wizard, but they can be added to the raw JSON configuration before the connector is created. For example, I need to add the following properties:

```json
"errors.tolerance": "all",
"errors.deadletterqueue.topic.name": "s3-connector-test-dlq",
"errors.deadletterqueue.topic.replication.factor": "1",
"format.output.envelope": false,
```

It is not possible to modify the raw JSON configuration once the connector has been created, and when updating the connector configuration, all custom properties such as the ones above are removed.

**Comment by vladoschreiner** [comment]
`errors.tolerance` is available in the cloud UI. Shouldn't be an issue

DQL and `format.output.envelope` are bugs. Should be added to the form.

> It is not possible to modify the raw JSON configuration once the connector has been created, and when updating the connector configuration, all custom properties such as the ones above are removed.

UX issue. Subject of the Programmatic API for Connectors project.
