### ISSUE TITLE
Feature Request: Add or Reassign Topic Partitions from the Console

### ISSUE THREAD

**Issue by brycefisher** [redpanda-data/console#727]
At my work, I've been advocating that we adopt this project and it's been _really_ well received. However, we've identified a few important but rarely used features that we still need to use the kafka cli tools for. Currently, we still have to run custom scripts to add and reassign topic partitions per broker.

I'm not entirely sure what the UI for this would look like, but I can imagine an "easy" mode that adds partitions and ensures each broker has the same number of topic partitions (plus-or-minus 1).

I can also imagine making the current topic partitions page editable for more advanced scenarios.

Perhaps something along these lines:
![imaginary-edit-partitions-ui](https://github.com/redpanda-data/console/assets/220106/26f4b625-e27d-41a0-81ab-e56c57bf0e05)

This feature is somewhat complex, so I imagine I've overlooked some important details.

**Comment by weeco** [comment]
Hey @brycefisher ,
this feature actually exists but it is part of the Redpanda Enterprise platform. Thus it is gated and you will need an enterprise license to use this. It can be used for rebalancing the number of partitions across brokers, which is especially helpful when you want to add or remove a broker in your cluster. In the past I had also use it to migrate a whole cluster by expanding and shrinking that cluster and moving the data via reassigning the partitions inbetween.
