### ISSUE TITLE
Feature Request: Restart process when sasl is updated/changed

### ISSUE THREAD

**Issue by alejandroEsc** [redpanda-data/console#734]
Currently the docker container allows you to set environment variables to set up sasl. However, it has been noted in the console helm chart, that there is no mechanism that allows you to restart the service in the case of changes to sasl. Is there a way/process to enable restarts without having to kill the pod to refresh the values?

**Comment by weeco** [comment]
Hey @alejandroEsc ,
no there's no way to do so. In the helm chart I assume we could use a checksum for the configuration and make that an annotation for the pod template so that the pods would be restarted. 

Would that make sense? Hot-reloading SASL credentials would require some effort to implement.

**Comment by alejandroEsc** [comment]
> Hey @alejandroEsc , no there's no way to do so. In the helm chart I assume we could use a checksum for the configuration and make that an annotation for the pod template so that the pods would be restarted.
> 
> Would that make sense? Hot-reloading SASL credentials would require some effort to implement.

It may be possible if we have can change the docker container to watch for changes in its env. Would you be open to this and  where would I be able to find the dockerfile for console?

**Comment by alejandroEsc** [comment]
> @alejandroEsc Not planned at the moment to hot-reload this, but the user should open an issue in the OSS console repo ideally

sounds good, ill close this ticket and open one there.
