### ISSUE TITLE
No cluster version displayed

### ISSUE THREAD

**Issue by dylanyht** [redpanda-data/console#735]
I am not showing the cluster version after installing with helm and docker, my kafka version is 3.4.0 and I am using kafka kraft mode

<img width="1277" alt="image" src="https://github.com/redpanda-data/console/assets/49978436/26c49969-d497-40e4-a770-dd7a602a7429">

**Comment by weeco** [comment]
Thanks @dylanyht , will check with @twmb to see what may be wrong there.

**Comment by ErykCh** [comment]
I confirm.

console version: redpandadata/console-unstable:master-87e7e0d
kafka: bitnami/kafka:3.5.0-debian-11-r3

![image](https://github.com/redpanda-data/console/assets/95491982/96d939e2-e7e7-4838-8ea2-9b4890314945)

console version: built June 20, 2023

![image](https://github.com/redpanda-data/console/assets/95491982/1db6ffa1-1610-45fb-a0ea-01f10bb15d34)

**Comment by twmb** [comment]
We just tested 3.4, can you check to see if this is still an issue?

**Comment by ErykCh** [comment]
Sorry for the delay, but it seemed to work fine on all environments.

Until this case.

New and still warm environment configured today. Yet producers and consumers are not connected to it.

![image](https://github.com/redpanda-data/console/assets/95491982/c8fd3628-4541-4fa8-af83-72a859191531)

Console version:  2.3.5
Kafka version:  bitnami/kafka:3.6.0-debian-11-r1
Kafka in kraft mode

**Comment by twmb** [comment]
@ErykCh do you have adocker-compose we can run to recreate this?

**Comment by ErykCh** [comment]
Sorry, everything is on openshift.

I make no promises, but if I find some time tomorrow, I will simulate this configuration on docker-compose.
