### ISSUE TITLE
hope can filter the topics.

### ISSUE THREAD

**Issue by RandyChen1985** [redpanda-data/console#741]
i have too much topics,  hope can filter to display ..
![image](https://github.com/redpanda-data/console/assets/1704661/f6543ae0-34ce-485c-978f-75f271412061)
![image](https://github.com/redpanda-data/console/assets/1704661/adbfbe92-04f4-4438-9562-c59c64b35cf3)

**Comment by RandyChen1985** [comment]
![image](https://github.com/redpanda-data/console/assets/1704661/67a2048d-1c54-487d-a79c-94a05cb155bd)

like this ..

**Comment by weeco** [comment]
In the table header (for the topic name) there's the magnifier icon. Click on that. The UI/UX for that is not intuitive, but we will improve that. Duplicate of #288

**Comment by RandyChen1985** [comment]
tks!
