### ISSUE TITLE
Saving unfiltered messages to file

### ISSUE THREAD

**Issue by felipepedrosapp** [redpanda-data/console#745]
When I have filtered messages and click on "save messages" button I expect that the messages that will be saved are the filtered ones but actually is saving all "original/unfiltered" messages. I don't understand too much about frontend/react but I think that can be solved using uiState messages!

**Comment by jvorcak** [comment]
Hi,

Thanks for your report, based on what I see we actually does download filtered messages (see the video https://www.loom.com/share/0cefc16db7614440bb0cd690a0e744ef). Is it maybe the refreshing thing that is the bad UX/bug here?
