### ISSUE TITLE
Allow download of messages as raw binary data

### ISSUE THREAD

**Issue by JFlath** [redpanda-data/console#758]
At present, we do some munging of data to display it in Console - this works really well for (e.g.) JSON messages, but in cases of raw binary messages the behaviour is a little bit less clear.

In the Console topic page, we show the UTF8-coerced version of the byte array, so for any byte that is a valid UTF8 codepoint we print the actual character (e.g. `0x4A` is rendered as `J`). There are some cases though where the byte value does not make it through Go's handling of this and instead gets rendered as the replacement character � (or rather `\ufffd`). 

The exact behaviour of the UI rendering here is certainly up for debate (perhaps we should have a distinct way of displaying messages that aren't valid UTF8?) however where this is a particular issue is with the _Copy value_ and _Save to file_ options, where these will actually give you the coerced version of the message, rather than it's actual value - for this, we should give the actual message back.

**Comment by weeco** [comment]
Can you describe the usecase of downloading "raw binary data"? Why do you want to download the raw binary data? That would help us prioritizing and possibly designing the feature more precisely for your usecase.

A whole kafka record as a binary? In what format would that be? Just the payload of the KafkaRecord value?

**Comment by kalmant** [comment]
Use case: Extract the payload from the messages and process them as you wish.

When you save a message (using "Save to File") or multiple messages using "Save Messages"  you're presented with a JSON file. In that file, there's a `value` and within that value there's a `payload` (and an `encoding` as well). I believe one should be able to treat that `payload` the same way as if it were read from the cluster with a client or through `rpk`. So yes, I'm mostly interested in the `payload` field.

Regarding the format: It could be base64, hex encoded or any common format. I believe base64 would be a good fit for this but maybe there are better options out there.

**Comment by weeco** [comment]
@kalmant I think the format (base64/hex vs binary) is a very important decision. This issue specifically mentions that messages shall be downloaded as raw binary which would force us to certain decisions such as - downloading the value for each message as a separate file. Did @JFlath create that issue on your behalf?

So far I could imagine downloading messages as a full record into a file with the following scheme:

```
{
  "key": "hex-encoded-key-bytes",
  "value": "hex-encoded-key-bytes",
  "headers": [{}], // Keys are strings, value hex encoded
  "timestamp": "", // unix ms
  // possibly more properties such as compression etc.
}
```

I think this would be the closest option to represent an actual Kafka record in a file so that you can process it however you want afterwards?

**Comment by kalmant** [comment]
Yes, I believe @JFlath created the issue based on what I brought up.

I can only speak for my specific use case ... but the best option for that use case would be:
```
{
    "otherFields": "whatever",
    "headers": [
        {
            "key": "publisher.instance",
            "value": {
                "payload": "test",
                "encoding": "text",
                "schemaId": 0
            }
        }
    ],
    "key": {
        "payload": "test",
        "encoding": "text",
        "schemaId": 0
    },
    "value": {
        "payload": "dGVzdA==",
        "encoding": "binary",
        "schemaId": 0
    }
}
```

The end result is still a JSON and if the encoding is binary then I can actually use the payload (after decoding it) vs. the current situation where payload can not be used.
