### ISSUE TITLE
Consider to add Pass-through database driver configuration

### ISSUE THREAD

**Issue by michaelpetri** [redpanda-data/console#781]
For at least Debezium SQL Server Connector it is possible to pass some driver configuration through the connector config:

> The Debezium connector provides for pass-through configuration of the database driver. Pass-through database properties begin with the prefix `driver.*.` For example, the connector passes properties such as driver.foobar=false to the JDBC URL.

Source: https://debezium.io/documentation/reference/stable/connectors/sqlserver.html#debezium-sqlserver-connector-pass-through-database-driver-configuration-properties

Since JDBC SQL Server Driver 10.2, microsoft enables SSL by default, which means, we have to disable SSL in e.g. local development set ups or for clients which don't care about security or privacy that much :see_no_evil: 

Source: https://learn.microsoft.com/en-us/sql/connect/jdbc/release-notes-for-the-jdbc-driver?view=sql-server-ver16#changes-in-102

I think it would make sense to implement those pass-through database driver configuration as a key/value input option in redpanda console in the future, because otherwise it's not possible to update configs through redpanda console and even worth we always see this error when someone visits the connector configuration page. In addition, this also spams logs since the validation endpoint reports this as an error.

![image](https://github.com/redpanda-data/console/assets/4114292/9773e6f7-92fc-4860-a6b3-f43ea77ebeaa)

**Comment by tomasz-sadura** [comment]
Hi. Let me ask some details to better understand you use case:
- what connector are you using?
- do you use Redpanda cloud, or you self-host it?
As a workaround you can specify configuration properties in the JDBC connection URL, will it work for you?

**Comment by michaelpetri** [comment]
1. I was using Debezium SQL Server connector
2. Self-hosted

The SQL Server Connector has no JDBC connection URL. Here a screenshot from console@2.2.x

![image](https://github.com/redpanda-data/console/assets/4114292/69926e6e-55b0-4702-8de7-ceab73305e67)

(I already tested 2.3.x but there is also no option to configure Pass-through database driver configuration)

Here is an example terraform connector config 

```terraform
resource "kafka-connect_connector" "my_connector_name" {
  name   = "my_connector_name"
  config = {
    "name"                                            = "my_connector_name"
    "connector.class"                                 = "io.debezium.connector.sqlserver.SqlServerConnector"
    "tasks.max"                                       = 10
    "table.include.list"                              = "dbo.my_table"
    "topic.prefix"                                    = "prefix"
    "topic.creation.default.partitions"               = 1
    "topic.creation.default.replication.factor"       = 1
    "database.encrypt"                                = false
    "database.applicationIntent"                      = "ReadOnly"
    "schema.history.internal.kafka.topic"             = "my_table.history"
    "schema.history.internal.kafka.bootstrap.servers" = var.kafka_bootstrap_server
    "value.converter"                                 = "io.confluent.connect.avro.AvroConverter"
    "value.converter.schema.registry.url"             = var.kafka_schema_registry_dsn
    "value.converter.schemas.enable"                  = true
    "key.converter"                                   = "io.confluent.connect.avro.AvroConverter"
    "key.converter.schema.registry.url"               = var.kafka_schema_registry_dsn
    "key.converter.schemas.enable"                    = true
    # JDBC driver config
    "driver.encrypt"                                  = false
    "driver.trustServerCertificate"                   = true
    "driver.integratedSecurity"                       = false
  }

  config_sensitive = {
    "database.hostname" = var.mssql_hostname
    "database.dbname"   = var.mssql_dbname
    "database.port"     = var.mssql_port
    "database.user"     = var.mssql_user
    "database.password" = var.mssql_password
    "database.names"    = var.mssql_dbname
  }
}
```

The whole `driver.*` part gets ignored by redpanda console. If it helps i can provide a test setup.

**Comment by tomasz-sadura** [comment]
All the inputs for a connector are auto generated based on what is reported by a Kafka Connect `/validate` endpoint for a specific connector. What you can do is add the fields in a JSON editor during connector creation.
You can also edit connector configuration as JSON in Console 2.3.

**Comment by michaelpetri** [comment]
Thanks for the feedback! 
So in order to fix this in a proper way, debezium would have to implement validation of the `driver.*` properties, so validate endpoint would return information about them?

**Comment by tomasz-sadura** [comment]
Yes
