### ISSUE TITLE
v2.3.0 does not decode Avro messages

### ISSUE THREAD

**Issue by AlexeyRaga** [redpanda-data/console#786]
Possible regression: v2.3.0 displays Avro messages as binaries:
<img width="684" alt="image" src="https://github.com/redpanda-data/console/assets/1394391/bda8833f-2225-4875-878c-4df2483b8a1c">

Previously (v2.2.x) it would detect Avro and would display deserialised payload.

**Comment by weeco** [comment]
Hey @AlexeyRaga ,
thanks for filing the issue. I think I'm able to reproduce this. While the protobuf deserialization is still working, the avro deserialization fails. I'll have a look tomorrow and work on a patch for this as soon as possible.

**Comment by weeco** [comment]
Hey @AlexeyRaga ,
sorry for silently closing this issue with the reference to the PR. If you have a chance could you test this Docker image please and let me know if the issue is fixed for you?

```
redpandadata/console-unstable:release-2.3-3f51fb9
```
