### ISSUE TITLE
Previews and values don't match

### ISSUE THREAD

**Issue by vladoschreiner** [redpanda-data/console#790]
When browsing the topic with Java Stacktrace messages, the value preview shows hexa codes (unwanted). Values are rendered correctly when the message is expanded.

Wanted: the preview to display should the same information as when it gets expanded.

See the screenshot:
<img width="1109" alt="KConnect topic browser" src="https://github.com/redpanda-data/console/assets/16268021/aba530ff-9b60-4c06-9c87-f14af1b539eb">

**Comment by rikimaru0345** [comment]
will be fixed when this is merged
https://github.com/redpanda-data/console/commit/7dade14ea128b6aebf9d71e8bcdb521e76732841#diff-f848fd0ad0fe409c99f72406f14f6bd61a8a74b18f758e182877526338f32895

**Comment by twmb** [comment]
Done, will be deployed with next release
