### ISSUE TITLE
bug: Avro messages are wrongly deserialized as plaintext in the topic message view

### ISSUE THREAD

**Issue by Pinimo** [redpanda-data/console#793]
In version `v2.3.0`, I cannot display Avro-encoded messages properly in the console anymore. The messages are parsed as `Utf8withcontrolchars` instead of `Avro` and the preview is empty. As a consequence, the topic view lacks usability by our service teams.

Other details: in our case, the messages are uncompressed; the link with the Schema registry seems OK (from the "Schema registry" section); JSON messages are still rendered normally (not deserialized as `Utf8withcontrolchars` but `Json`, and neat preview and detail view); last, we were able to rollback to `v2.2.4` without problem to "fix" the bug.

Here are 2 snapshots of expected and actual behavior, on the same message of the same non-production topic (the "expected" case comes from version `v2.2.4`). In the actual behavior, you can see the `Value` preview field is empty, and that the contents are not rendered as a deserialised Json object (from Avro), but rather as plain UTF8 text.

Thanks for your help!

| Case | Snapshot |
|-------------|------------|
| Expected behavior | ![image](https://github.com/redpanda-data/console/assets/14152858/4249a2b7-e1ca-4296-872d-db65227db814) | 
| Actual behavior | ![image](https://github.com/redpanda-data/console/assets/14152858/2fea357d-e232-4cfb-b9b0-788934bdafe6) |

**Comment by weeco** [comment]
Hey @Pinimo ,
I think this is the same as https://github.com/redpanda-data/console/issues/786 . I posted a Docker image to test there, but haven't got feedback back. Are you able to test it against your cluster before I proceed and add a tag for a new release there?
