### ISSUE TITLE
Not able to add avro configs in redpanda

### ISSUE THREAD

**Issue by VipulZopSmart** [redpanda-data/console#803]
I've spun up a docker image and connected to remote brokers by using this command: 

`docker run -p 8080:8080 -e KAFKA_BROKERS=pkc-4r000.europe-west1.gcp.confluent.cloud:9092 -e KAFKA_TLS_ENABLED=true -e KAFKA_SASL_ENABLED=true -e KAFKA_SASL_USERNAME=xxx -e KAFKA_SASL_PASSWORD=xxx docker.redpanda.com/redpandadata/console:latest`

however, I'm not able to connect to the schema registry, can someone please help me with how can I give configs for the schema registry?

**Comment by VipulZopSmart** [comment]
@weeco can you please help here?

**Comment by weeco** [comment]
Hey @VipulZopSmart ,
did you see the reference config and how the env variables are constructed here: https://docs.redpanda.com/docs/reference/console/config/#environment-variables ?

e.g. `KAFKA_SCHEMAREGISTRY_ENABLED=TRUE` as well as the urls must be set.

**Comment by VipulZopSmart** [comment]
Thanks!
