### ISSUE TITLE
[frontend] host color is blue while partitions and lag is while + red

### ISSUE THREAD

**Issue by victorgawk** [redpanda-data/console#809]
Route: Cluster -> Consumer Groups -> topic -> tab: Partitions -> view: Members

The `host` color is blue while `partitions` and `lag` color is white + red.
![image](https://github.com/redpanda-data/console/assets/6736720/72e00600-350e-4f1a-9556-7db01902d1a2)

**Comment by weeco** [comment]
Hey, this should already be fixed with the latest version on master. We are migrating from AntD to the Redpanda component migration, so such inconsistencies are expected until we are done with the migration. This specific case (the Tag component) has been migrated recently.
