### ISSUE TITLE
AVRO not getting deserialized correctly in some cases

### ISSUE THREAD

**Issue by NNicoletti** [redpanda-data/console#818]
Hi all,

My organization is currently on console `v2.2.4` in a K8's environment and we're using avro serialization to send large amounts of data. In all but one of them the data is getting sent through as avro, but in the one case it's showing as binary in the console:

![image](https://github.com/redpanda-data/console/assets/49345843/0a1ceaea-75ba-48f9-82b4-788151768cf3)

This particular topic is getting the largest amount of data in each message, but I tested sending a "blank" message to see and it still comes through as binary and sometimes plaintext. 

This is happening on the same build as the below, which is correct:

![image](https://github.com/redpanda-data/console/assets/49345843/df914180-b4c3-48f7-99ba-db286bfc89d4)

I've been struggling to fix this on my own and don't know much about red panda as a whole. I've more or less eliminated the idea that it's on the Producer side as both of those screenshots are coming from the same producer and use the same functions to serialize.

I did see this issue (https://github.com/redpanda-data/console/issues/786), but we're on 2.2.4 and wasn't sure if that bug was introduced as a regression in 2.3.0 or just didn't get caught until then.

Any ideas? Would upgrading to the most recent build (`latest` or `2.3.1` more likely) fix it?

**Comment by weeco** [comment]
Hey,
a 31kiB is indeed a very large payload, and likely this would fail to open in the frontend if parsed to JSON correctly - so soon we will be capping the max size. However, as of today the deserialization should still work.

Please test the latest v2.3.1 version to see if this is fixed. Something that has caused similar issues in our community were invalid Avro schemas, that worked fine with other libraries that don't adhere strictly to the Avro specification. One such example would be using enum values with invalid characters (e.g. `COLOR.RED` where `.` is an invalid char). We are also working on improvements that hint why the deserialization has failed, but this will take a little more until this is ready to be tested.

**Comment by NNicoletti** [comment]
@weeco appreciate it! We'll attempt the update to `2.3.1` and hope for the best.

Is there a current size limit for avro deserialization? And what's the planned max size?

Appreciate the help!

**Comment by weeco** [comment]
We don't have a size limit currently. As for the planned size, we'll conduct tests to see what max size is feasible to handle in most browsers. I think it will be few KiB's only, since the browser resources are very limited

**Comment by weeco** [comment]
Closing this for now. FWIW there's another patch which may help. Released as v2.3.2. If you still face issues I'll reopen this issue.
