### ISSUE TITLE
Schema Registry: `NaN` used as default version when browsing schemas

### ISSUE THREAD

**Issue by hhromic** [redpanda-data/console#824]
Hi, first of all thanks for the Redpanda Console. It is really a nice tool!

While playing around with the [Redpanda Quickstart](https://docs.redpanda.com/current/get-started/quick-start/), I noticed that the [Schema Registry section](http://localhost:8080/schema-registry) in the Redpanda Console seems to have a navigation bug regarding schema versions.

At the time of this writing, the Redpanda Console version used in the Compose file was `v2.3.1`.

Consider the following sequence of `curl` calls to setup a new schema with two versions (examples from [here](https://docs.redpanda.com/current/manage/schema-registry/)):
```
curl -s \
  -X POST \
  "http://localhost:18081/subjects/sensor-value/versions" \
  -H "Content-Type: application/vnd.schemaregistry.v1+json" \
  -d '{"schema": "{\"type\":\"record\",\"name\":\"sensor_sample\",\"fields\":[{\"name\":\"timestamp\",\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},{\"name\":\"identifier\",\"type\":\"string\",\"logicalType\":\"uuid\"},{\"name\":\"value\",\"type\":\"long\"}]}"}' \
  | jq
```
```
curl -s \
  -X POST \
  "http://localhost:18081/subjects/sensor-value/versions" \
  -H "Content-Type: application/vnd.schemaregistry.v1+json" \
  -d '{"schema": "{\"type\":\"record\",\"name\":\"sensor_sample\",\"fields\":[{\"name\":\"timestamp\",\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},{\"name\":\"identifier\",\"type\":\"string\",\"logicalType\":\"uuid\"},{\"name\":\"value\",\"type\":\"double\"}]}"}' \
  | jq
```

If you browse the newly created [`sensor-value` schema](http://localhost:8080/schema-registry/sensor-value) in the Redpanda Console, the following two things can be observed:

* The initial schema page will load and the browser current URL will change to:
   ```
   http://localhost:8080/schema-registry/sensor-value?version=undefined
   ```
* In the schema details view, the _Version_ select box will default to `NaN`.
* If you try to manually browse to `?version=2`, it goes back to `?version=undefined` and the same as above happens.

Despite that, selecting a specific version in the _Version_ select box does work correctly.
I think the problem is that the `version` URL query param is not being recognised and falling back to `undefined` on load.

<img width="80%" alt="console-capture" src="https://github.com/redpanda-data/console/assets/5802993/7660d154-2a27-484b-aab1-4a25e6df84e6">

**Comment by weeco** [comment]
hey @hhromic ,
thanks for reporting this. We are currently re-working the entire schema registry management and would like to invite you to beta-test this to provide early feedback for us. I understand that the current situation is not ideal, but given that the experience will be very different in the near future, I'm not sure whether it's worth to address this issue in the current v2.3 version.

I'll post here once the new schema management functionality is ready to test.

**Comment by hhromic** [comment]
> I'll post here once the new schema management functionality is ready to test.

Thanks for the invitation to test the re-worked UI.
I can give it a try to the beta whenever is ready 👍.

> I'm not sure whether it's worth to address this issue in the current v2.3 version.

From the look of the issue, maybe is simple to fix. I am not 100% familiar with the frontend code but will try to see where the problem might be. It is evident that probably it is just a variable initialization missing somewhere. I think it is worth to chase for users not wanting to migrate to newer versions "just yet".

**Comment by twmb** [comment]
Fixed in next release
