### ISSUE TITLE
Db2 source connector not supported

### ISSUE THREAD

**Issue by rupurt** [redpanda-data/console#826]
Hi,

I'm trying to configure a Db2 source connector via the Redpanda console and it looks like it can't validate the connector.

```
CreateConnector.tsx:361 Uncaught (in promise) ConnectorValidationError: Error: Failed to validate Connector config: java.lang.NoClassDefFoundError: Could not initialize class io.debezium.connector.db2.Db2Connection (500)
    at _callee3$ (CreateConnector.tsx:361:27)
    at tryCatch (regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (regeneratorRuntime.js:125:22)
    at Generator.throw (regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (asyncToGenerator.js:3:20)
    at _throw (asyncToGenerator.js:25:9)
```

![Screenshot from 2023-09-01 10-19-52](https://github.com/redpanda-data/console/assets/680789/d758aa9a-84a8-4f47-be36-33b112d89d3d)

**Comment by weeco** [comment]
Hey @rupurt ,
could you share a quick video showing how to reproduce this? Please also share the response of the /validate request if possible. 

Based on the shared error it seems like you were requesting a connector plugin that is not installed in the target connect cluster. By default this should not be possible, unless you modified the class in the JSON editor I believe.

**Comment by rupurt** [comment]
Just updated to the latest debezium connect 2.4 that was released last night and it's fixed. Sorry, I thought it was a bug in Redpanda console...
