### ISSUE TITLE
protobuf fields are camelCased even if the field is not in the proto schema

### ISSUE THREAD

**Issue by brokenjacobs** [redpanda-data/console#839]
We are testing proto3 serialization with the schema registry and have noticed an odd issue:

we have a proto schema with fields like:
'''
message OurData { string part_number = 1; string source_id = 2; string site_id = 3; google.protobuf.Timestamp readout_time = 4;}
'''
But when we get messages in the redpanda console:
'''
{
"partNumber":"CA04430000"
"sourceId":"54188"
"siteId":"HQTW"
"readoutTime":"2023-09-13T11:50:47.895Z"
}
'''

Instead of part_number, source_id, site_id, readout_time. I've tried another kafka client and I get the expected result so it seems like something the redpanda console (or golang) is doing here.

**Comment by michaelandrepearce** [comment]
Good std convention is they should be camel cased but they don't have to be, it's legal for them to other casing type , Schema registery shouldnt be altering the field name is should be kept as sent.

**Comment by brokenjacobs** [comment]
Thanks! Looks like we need to add json_name field options if we want the behavior we expect.
