### ISSUE TITLE
updation of right scroll bar for better looking UI

### ISSUE THREAD

**Issue by harshalhonde21** [redpanda-data/console#897]
![ss](https://github.com/redpanda-data/console/assets/105191619/3108d36f-f665-412e-aec4-49626e9a99cc)

There is default scroll bar which not looking nice so by enhacement of the scroll the website look will more better.

**Comment by harshalhonde21** [comment]
please assign this issue to me

**Comment by weeco** [comment]
The screenshot you showed is the Redpanda website. This repository is about Redpanda Console and not the redpanda.com website.
