### ISSUE TITLE
failed to load yaml config

### ISSUE THREAD

**Issue by c0desurfer** [redpanda-data/console#904]
We have a strange issue on multiple but not all Windows machines when using the release exe file. We are getting the following error.

`{"level":"fatal","msg":"failed to load yaml config","error":"1 error(s) decoding:\n\n* 'license' expected type 'string', got unconvertible type 'map[string]interface {}', value: 'map[key:<HASH>]'"}`

We tried to skip using the yaml config files by using env variables only but even with the following bat file we are getting the exact same error.

```
set KAFKA_BROKERS=bootstrap.domain.uk:1234
set KAFKA_SASL_ENABLED=true
set KAFKA_SASL_MECHANISM=SCRAM-SHA-512
set KAFKA_SASL_USERNAME=USER
set KAFKA_SASL_PASSWORD=PASSWORD
set KAFKA_TLS_ENABLED=true
set KAFKA_TLS_CAFILEPATH=./cert.pem
set KAFKA_SCHEMAREGISTRY_ENABLED=true
set KAFKA_SCHEMAREGISTRY_URLS=https://sr.domain.uk
set KAFKA_SCHEMAREGISTRY_TLS_ENABLED=true
set KAFKA_SCHEMAREGISTRY_TLS_CAFILEPATH=./ca.pem
set SERVER_LISTENPORT=9011

start redpanda-console.exe
start http://localhost:9011
```

This setup still gives the following error.

`{"level":"fatal","msg":"failed to load yaml config","error":"1 error(s) decoding:\n\n* 'license' expected type 'string', got unconvertible type 'map[string]interface {}', value: 'map[key:<HASH>]'"}`

Do you have any idea why this happens? What "license" does it try to load?

**Comment by bojand** [comment]
Hello,

The [license config property](https://docs.redpanda.com/current/reference/console/config/) is for enterprise features, but is not required to run Console and use any of the open source functionality. So somehow the value is being set to something that cannot be decoded properly.

Do you perhaps have `LICENSE` or `CONFIG_FILEPATH` environmental variables set (perhaps for some other processes)?

In the YAML config file can you explicitly set `license: ""` and then start console by either setting the `CONFIG_FILEPATH` env var to the path of the config file, or using the `-config.filepath=<path to config file>` command like argument. Does it change anything?

**Comment by c0desurfer** [comment]
You hit the nail on the head. The windows machine had an environment variable named `LICENSE_KEY`. I even was able to reproduce this on my Macbook by simply running `export LICENSE_KEY="BLAH"`. I guess this should be fixed because I bet others will run into it as well :) Thank you!
