### ISSUE TITLE
ACL UI Suggestions/Issues

### ISSUE THREAD

**Issue by wzzzrd86** [redpanda-data/console#913]
Suggested ACL UI issues

 1. When creating ACLs through UI, user is not required to add a mask value in text field. If there is no value in text field, the ACL is not created.
2. If the user creates ACLs using * for text field and checking all the options except "All", the subsequent details view can show some of the checks missing, while the backend list of ACLs for this user has a full list (partial data retrieval, verified with Esteban).
3. Upon clicking the "OK" button from the ACLs detailed view, the user is shown "ACLs for User xxxxx has been updated" even if the operation failed. The specific ACL changes are not shown, it's impossible to track whether the changes to a certain part of the form have been saved successfully.
4. Clicking "OK" on a form where some of the checks were missing due to UI glitch, updates the backed to remove the said ACLs from user's account. It's especially important, because not all of the form data is viewed at once, and pop-up window has to be scrolled to see all values. (User may not be aware that ACLs were missing from the form view when clicking "OK" to close window and may not be aware the ACLs would be removed)

**Comment by jvorcak** [comment]
@wzzzrd86 is this the lastest version? Because there has been some changes to this module and I think it might have solved some of these

**Comment by jvorcak** [comment]
1. fixed in https://github.com/redpanda-data/console/pull/1390
