### ISSUE TITLE
Filter help text is obscured

### ISSUE THREAD

**Issue by ivpanda** [redpanda-data/console#915]
When I open the filters in the message viewer and click to look at the examples, the example box goes off-screen and there's no way to read the information at the top of it: 

<img width="1013" alt="image" src="https://github.com/redpanda-data/console/assets/129790723/4771b256-2567-4bf6-bdbb-ab49765d5ded">

**Comment by malinskibeniamin** [comment]
Looks like a "modal within a modal" situation, but I haven't taken a closer look

**Comment by ivpanda** [comment]
@malinskibeniamin Is it possible to open our documentation sidebar in this situation?

**Comment by malinskibeniamin** [comment]
If you mean the drawer, then yes.

If you mean the actual sidebar, then it would only be shown when console is running in embedded mode, because that component is in the cloud UI, not directly in console.

**Comment by ivpanda** [comment]
I mean the drawer, yeah. It might be a solution to this?

**Comment by jvorcak** [comment]
<img width="1372" alt="Screenshot 2023-12-09 at 20 56 02" src="https://github.com/redpanda-data/console/assets/1083817/378efc77-1882-4215-849a-3d7a939d3ea1">

Would this work @ivpanda ?

I wanted to open it from the right, but we have that place reserved for toasts (upper right corner), so I was afraid there could be some corner case where the close icon could be covered with a toast.

**Comment by ivpanda** [comment]
@jvorcak that's exactly what I meant, but on the right. We do this currently— below, the example is when a user clicks one of the options in the "Kafka API" tab for a cluster: 

<img width="1352" alt="image" src="https://github.com/redpanda-data/console/assets/129790723/ed350941-717c-44d7-bc6a-15aa63060cfd">

**Comment by jvorcak** [comment]
@ivpanda the only reason why I positioned it on the left is that we can have an active toast that is in top right corner that can interfere with a X for closing. We still have a cancel button at the bottom though. Should I keep it on the left or position on the right?

**Comment by twmb** [comment]
Merged, awaiting imminent release, closing
