### ISSUE TITLE
Return lost features.

### ISSUE THREAD

**Issue by henriquelsmti** [redpanda-data/console#931]
Over time, the console has lost some functionalities. Some time ago, we lost the ability to edit the connector via JSON, which prevents the alteration of some connector consumer or producer configurations. Recently, the task restart button was removed. In some cases, when restarting the connector, the tasks aren't restarted (probably due to a bug in Kafka Connect). I recently created a Debezium connector, which failed due to database permission issues. After fixing the permissions in the database, I attempted to restart the connector using the general button, but it had no effect. I had to restart the task via the REST API. With these reasons in mind, I would like to request the return of the JSON editor as an additional way to edit the connector and the return of the restart button in the task grid.

**Comment by weeco** [comment]
Hey @henriquelsmti , we already re-added the JSON editor in the latest versions. For example you can give this version a try: `redpandadata/console-unstable:master-e535c86`. Also the restart button should restart the connector as well as all its tasks. If you are running and older Kafka connect version this optional parameter on the restart command may not be supported. I'm not entirely sure what Kafka connect version this was added, but I'm fairly confident that this works in Redpanda Cloud.

You can try it yourself by executing `POST /connectors/hdfs-sink-connector/restart?includeTasks=true`

Does this address all your questions or did I miss anything?

**Comment by henriquelsmti** [comment]
Nice!
 I'm using confluentinc/cp-kafka-connect:6.2.9 and it doesn't have the 'includeTasks' parameter. I'll plan the Kafka Connect upgrade. Thanks!

**Comment by henriquelsmti** [comment]
Nice!
 I'm using confluentinc/cp-kafka-connect:6.2.9 and it doesn't have the 'includeTasks' parameter. I'll plan the Kafka Connect upgrade. Thanks!
