### ISSUE TITLE
Clicking the restart button for the connector will not restart the failed subtasks.

### ISSUE THREAD

**Issue by cobolbaby** [redpanda-data/console#948]
Clicking the restart button for the connector will not restart the failed sub-tasks, such as kafka-connect-jdbc. This should be a bug of Kafka Connect (confluentinc/cp-kafka-connect:5.5.9). 

Before console v2.3.x, I could restart each subtask individually, but the new version does not seem to support this.

**Comment by weeco** [comment]
This endpoint feature was added in Kafka Connect ~2 years ago (equals to Confluent Platform 7.0). The Kafka connect version you are running seems around 4 years old. I think you should either update your Kafka connect cluster or continue with an old Console version until you are ready to update your connect cluster. We tweak Console to simplify the UX (which includes certain abstractions such as individual task restarting).

**Comment by cobolbaby** [comment]
> This endpoint feature was added in Kafka Connect ~2 years ago (equals to Confluent Platform 7.0)

Yes, It was add in Kafka 3.0.0 (links to https://issues.apache.org/jira/browse/KAFKA-4793)

> The Kafka connect version you are running seems around 4 years old.

To be precise, it has only been three years since the v2.5.1 version (equals to Confluent Platform 5.5) was released.

![2023-12-10 18-22-23屏幕截图](https://github.com/redpanda-data/console/assets/11460848/77c9c7b9-5e3e-42ad-ac4e-311468028c2b)

**Comment by cobolbaby** [comment]
> We tweak Console to simplify the UX (which includes certain abstractions such as individual task restarting).

IMO, for Kafka versions before 3.x, the console should consider implementing backend compatibility.

**Comment by weeco** [comment]
I see how enterprises will take their additional time before doing an upgrade to Kafka 3.x, but why would they wait so long to upgrade Kafka Connect?

I think it is reasonable to rely on 2-year old features for less-critical functionality or ask the users to stick to an older Console version where this would still be supported. Supporting older Kafka versions is thanks to the Kafka API versioning (and the flexible versions support in our Kafka client) relatively easy, but doing the same for Kafka Connect or schema registry is less comfortable from a development & maintenance perspective.

**Comment by cobolbaby** [comment]
> I see how enterprises will take their additional time before doing an upgrade to Kafka 3.x, but why would they wait so long to upgrade Kafka Connect?

I've never tried upgrading Kafka Connect to version 3.x without updating Kafka itself. Maybe I can test if it's possible.
