### ISSUE TITLE
:calendar: Release policy :grey_question: 

### ISSUE THREAD

**Issue by adriens** [redpanda-data/console#959]
# :grey_question: About

Hi, I'm a `[endoflife.date`](https://endoflife.date/apache-kafka) contributor and a [`redpanda-data/console`](https://github.com/redpanda-data/console) aficionado.
I would like to add the console to [endoflife.date](https://endoflife.date/) and wonder if you have some policy like : 

- LTS
- Support
- ...

So I could add it, next to [Apache Kafka](https://endoflife.date/apache-kafka) one :thought_balloon:

**Comment by weeco** [comment]
Hey @adriens ,
sorry for my late response. As of today we don't have LTS for releases. We will always support security patches and bugfixes for the latest released minor version for sure and we have setup security scans for the last two minor versions where we provide critical security fixes. 

Generally we recommend users to use the latest Redpanda Console version regardless of what Redpanda or Apache Kafka version they use.

**Comment by adriens** [comment]
Hi @weeco , thanks a lot for the answer :+1: 

> sorry for my late response. 

That's fine :smile_cat: 

> As of today we don't have LTS for releases. We will always support security patches and bugfixes for the latest released minor version for sure and we have setup security scans for the last two minor versions where we provide critical security fixes.

So : 

- No `LTS`
- May I consider that only the latest version is supported ? (that would match _"Generally we recommend users to use the latest Redpanda Console version regardless of what Redpanda or Apache Kafka version they use."_)
