### ISSUE TITLE
Message viewer not support filtering queries by timestamp

### ISSUE THREAD

**Issue by cobolbaby** [redpanda-data/console#966]
The latest version(redpandadata/console-unstable:master-81e6897) transitions the request method from websocket to restful interface? Is there any other reason besides simplifying implementation?

But there are some imperfections at present, such as the message viewer not support filtering queries by timestamp.

![2023-12-14 12-38-54屏幕截图](https://github.com/redpanda-data/console/assets/11460848/2b55f0a4-caa3-449b-9d41-0e2a2f95a97e)

And If I choose 'START OFFSET' as 'Newest,' the data retrieval method transitions from the previous WebSocket protocol to the current HTTP chunk. I have observed multiple backend response errors at present, and personally, I feel that WebSocket is more stable than HTTP long polling.

![2023-12-15 18-42-35屏幕截图](https://github.com/redpanda-data/console/assets/11460848/d40ddaad-7a52-472c-b68c-ff769fdde819)

**Comment by weeco** [comment]
We switched to HTTP streaming, becuase many users reported issues with using Websockets in their environment. Several reverse proxies do not support it by default. Do you notice any disadvantages with this approach?

**Comment by weeco** [comment]
I did not notice the title of this issue until now. There may be a problem with the timepicker, we'll investigate this within the next few days.

**Comment by cobolbaby** [comment]
> Do you notice any disadvantages with this approach?

If I choose 'Start Offset' as 'Newest,' the data retrieval method transitions from the previous WebSocket protocol to the current HTTP chunk. I have observed multiple backend response errors at present, and personally, I feel that WebSocket is more stable than HTTP long polling.

**Comment by weeco** [comment]
@cobolbaby Thanks for sharing, are you able to reproduce this or even better to give us a way to reproduce this? We have not seen this before and have tested this in different environments including those where websockets were problematic before.

**Comment by weeco** [comment]
Possibly this is a timeout issue , e.g. a request cancelled by a reverse proxy given that the request with a duration of >30s failed but the other with 26s succeeded?

**Comment by cobolbaby** [comment]
> are you able to reproduce this or even better to give us a way to reproduce this

Please refer to [console deployment configuration](https://github.com/cobolbaby/dockerize-and-ansible/tree/master/kafka/admin) .
