### ISSUE TITLE
Redpanda Console KStream State Store

### ISSUE THREAD

**Issue by BenL-M** [redpanda-data/console#987]
Hello, I am new to Redpanda. I have an application that uses a Kafka steam. Is is possible to view and edit what is inside the state store using Redpanda Console?

**Comment by weeco** [comment]
Hey @BenL-M ,
no it isn't. I'm not sure what information about Kafka streams applications we could even retrieve without requiring the applications installing some extra dependency that reports these information. If you have an idea let us know, but based on my current understanding theres not much that we could do

**Comment by BenL-M** [comment]
Ok. Good to know!
